/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trixware.erp.prodezydesktop.examples;


import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JViewport;
import trixware.erp.prodezydesktop.Model.Proman_User;
import trixware.erp.prodezydesktop.Model.StaticValues;


/**
 *
 * @author Rajesh
 */
public class ButtonPanel extends JPanel {

    String resource = "" , resourceType = "" ;
    
    /**
     * Creates new form ButtonPanel
     */
    public ButtonPanel () {
     //   initComponents ();
        
//        jButton1.addActionListener ( saveRecord );
 //       jButton6.addActionListener ( listemBPClose );
       
    }

    public ButtonPanel ( String _resource  , String _resourceType ) {
     //   initComponents ();
        
        jButton1.addActionListener ( saveRecord );
        jButton6.addActionListener ( listemBPClose );
        
        try{
            StaticValues.checkUserRolePermission( _resourceType, _resourceType);
        }catch(Exception e){
            StaticValues.writer.writeExcel (resource , resource , e.getClass ().toString () , Thread.currentThread ().getStackTrace ()[ 1 ].getLineNumber () + "" , e.getMessage () , StaticValues.sdf2.format ( Calendar.getInstance ().getTime () ) );
        }

        if( Proman_User.isCanCreate ()  ){
           // jButton1.setVisible ( true );
        }else {
            //jButton1.setVisible ( false );
        }
        
        if( Proman_User.isCanEdit ()  ){
            //jButton4.setVisible ( true );
        }else {
           // jButton4.setVisible ( false );
        }
        
        if( Proman_User.isCanImport ()  ){
           // jButton7.setVisible ( true );
        }else {
           // jButton7.setVisible ( false );
        }
        
        if( Proman_User.isCanExport ()  ){
            //jButton3.setVisible ( true );
        }else {
          //  jButton3.setVisible ( false );
        }
        
        if( Proman_User.isCanExportToPDF ()){
            //jButton3.setVisible ( true );
        }else {
          //  jButton3.setVisible ( false );
        }
        
        if( Proman_User.isCanDisable ()){
            //jButton3.setVisible ( true );
        }else {
          //  jButton3.setVisible ( false );
        }
        
        if( Proman_User.isCanRead ()){
            //jButton3.setVisible ( true );
        }else {
          //  jButton3.setVisible ( false );
        }
        
        if( Proman_User.isCanSeeReports ()){
            //jButton3.setVisible ( true );
        }else {
          //  jButton3.setVisible ( false );
        }
        
    }
    
    
    
     ActionListener listemBPClose = new ActionListener () {
        @Override
        public void actionPerformed ( ActionEvent e ) {
            
            //JViewport c = (JViewport) HomeScreen.scroll.getComponents ()[0];
            //Component c2= c.getView ();
          
            //UserRolePermissionMaster c1 = new UserRolePermissionMaster ();
            //if( c1.getClass ().getSimpleName ().equals (  c2.getClass ().getSimpleName () )){
            
            HomeScreen.home.removeForms ();
            
            //}
        }
    };
     
     
     ActionListener saveRecord = new ActionListener(){
        @Override
        public void actionPerformed ( ActionEvent e ) {
            JViewport c = (JViewport) HomeScreen.scroll.getComponents ()[0];
            Component c2= c.getView ();
            
            String openForm = c2.getClass ().getSimpleName () ;
            
            switch(openForm){
                
                case "UtilitiyMasters" :
                    
                    JOptionPane.showMessageDialog ( null, "You have selected to save utility Master form " );
                    
                    break;
                    
                default :
                    JOptionPane.showMessageDialog ( null, "default action triggered" );
                    
                
            }
            
            
        } 
    };
     
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    /*@SuppressWarnings( "unchecked" )
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setBackground(new java.awt.Color(19, 19, 19));
        setMinimumSize(new java.awt.Dimension(809, 51));
        setPreferredSize(new java.awt.Dimension(1115, 60));
        setLayout(null);

        jButton1.setBackground(new java.awt.Color(51, 51, 51));
        jButton1.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trixware/erp/prodezydesktop/Utilities/assets/icons/48x48/iconfinder_floppy_285657.png"))); // NOI18N
        jButton1.setToolTipText("<html>Save Record to Database<br>Save the record in the currently open form into database</html>");
        jButton1.setBorder(null);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setOpaque(false);
        jButton1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(300, 6, 48, 48);

        jButton2.setBackground(new java.awt.Color(51, 51, 51));
        jButton2.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilities/assets/icons/48x48/disable_on.png"))); // NOI18N
        jButton2.setToolTipText("<html>Disable Selected Record<br>Disable a selected record in database</html>");
        jButton2.setBorder(null);
        jButton2.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilities/assets/icons/48x48/disable_off.png"))); // NOI18N
        jButton2.setEnabled(false);
        jButton2.setOpaque(false);
        jButton2.setPreferredSize(new java.awt.Dimension(48, 48));
        add(jButton2);
        jButton2.setBounds(420, 6, 48, 48);

        jButton3.setBackground(new java.awt.Color(51, 51, 51));
        jButton3.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilities/assets/icons/48x48/reload.png"))); // NOI18N
        jButton3.setToolTipText("<html>Reset current form<br>Clears all selections and empties all fields from currently open form</html>");
        jButton3.setBorder(null);
        jButton3.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilities/assets/icons/48x48/reload_off.png"))); // NOI18N
        jButton3.setOpaque(false);
        jButton3.setPreferredSize(new java.awt.Dimension(48, 48));
        add(jButton3);
        jButton3.setBounds(540, 6, 48, 48);

        jButton4.setBackground(new java.awt.Color(51, 51, 51));
        jButton4.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilities/assets/icons/48x48/xls_up.png"))); // NOI18N
        jButton4.setToolTipText("<html>Import from Excel<br>Opens a browser to select a file from storage. An Excel (.xls) needs to be selected for fetching the data from and add data to system. The Excel file needs to have data in prescribed format.</html>");
        jButton4.setBorder(null);
        jButton4.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilities/assets/icons/48x48/xls_up_off.png"))); // NOI18N
        jButton4.setOpaque(false);
        add(jButton4);
        jButton4.setBounds(660, 6, 0, 0);

        jButton5.setBackground(new java.awt.Color(51, 51, 51));
        jButton5.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilities/assets/icons/48x48/xls_down.png"))); // NOI18N
        jButton5.setToolTipText("<html>Export to Excel<br>Export the data in a newly created excel file and show the download location after successful download </html>");
        jButton5.setBorder(null);
        jButton5.setOpaque(false);
        jButton5.setPreferredSize(new java.awt.Dimension(48, 48));
        add(jButton5);
        jButton5.setBounds(770, 6, 48, 48);

        jButton6.setBackground(new java.awt.Color(51, 51, 51));
        jButton6.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilities/assets/icons/48x48/close.png"))); // NOI18N
        jButton6.setToolTipText("Close : Closes this form and loads Home screen");
        jButton6.setBorder(null);
        jButton6.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilities/assets/icons/48x48/close_off.png"))); // NOI18N
        jButton6.setOpaque(false);
        jButton6.setPreferredSize(new java.awt.Dimension(48, 48));
        add(jButton6);
        jButton6.setBounds(880, 6, 48, 48);
    }// </editor-fold>//GEN-END:initComponents

    
    */
    
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    // End of variables declaration//GEN-END:variables

     
}
