/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trixware.erp.prodezydesktop.examples;

import java.awt.Toolkit;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Vector;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.apache.poi.hssf.usermodel.HSSFCellStyle;
import org.apache.poi.hssf.usermodel.HSSFWorkbook;
import org.apache.poi.hssf.util.HSSFColor;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.CellStyle;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;
import trixware.erp.prodezydesktop.Utilities.DB_Operations;

/**
 *
 * @author Rajesh
 */
public class CalibrationAgencyMaster extends javax.swing.JPanel {

    /**
     * Creates new form CustomerMaster
     */
    public CalibrationAgencyMaster() {
        initComponents();
    }

    public void loadContent() {
        try {
            ResultSet result = DB_Operations.getMasters("calibration_agency");
            // jTable1.setModel(DbUtils.resultSetToTableModel(result)); 

            if (result != null) {
                jTable1.setModel(buildTableModel(result));

                jTable1.getColumnModel().getColumn(0).setMinWidth(0);
                jTable1.getColumnModel().getColumn(0).setMaxWidth(0);
            }

       /*     result = DB_Operations.getMasters("");

            while (result.next()) {
                jComboBox2.addItem(result.getString("RM_TYPE") + " ( " + result.getString("RM_CTG") + " )");
            } */

        } catch (SQLException e) {

        }

        jButton1.setEnabled(false);
    }

    public static DefaultTableModel buildTableModel(ResultSet rs)
            throws SQLException {

        ResultSetMetaData metaData = rs.getMetaData();

        // names of columns
        Vector<String> columnNames = new Vector<String>();
        int columnCount = metaData.getColumnCount();
        for (int column = 1; column <= 4; column++) {
            columnNames.add(metaData.getColumnName(column));
        }

        // data of the table
        Vector<Vector<Object>> data = new Vector<Vector<Object>>();
        while (rs.next()) {
            Vector<Object> vector = new Vector<Object>();
            for (int columnIndex = 1; columnIndex <= 4; columnIndex++) {
                vector.add(rs.getObject(columnIndex));
            }
            data.add(vector);
        }

        return new DefaultTableModel(data, columnNames);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextField14 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jTextField15 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jTextField16 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jTextField17 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jComboBox5 = new javax.swing.JComboBox<>();
        jPanel6 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jTextField21 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jTextField22 = new javax.swing.JTextField();
        jTextField23 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jTextField5 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();

        jLabel21.setText("City");

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mumbai", "Pune", "Nagpur", "Nashik", "Thane", "Pune", "Aurangabad", "Solapur", "Thane", "Palghar", "Thane", "Amravati", "Thane", "Akola", "Thane", "Dhule", "Jalgaon", "Nanded", "Kolhapur", "Latur", "Raigad", "Thane", "Sangli", "Nashik", "Ahmednagar", "Kolhapur", "Chandrapur", "Parbhani" }));

        setPreferredSize(Toolkit.getDefaultToolkit().getScreenSize());
        setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Calibration Agencies", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Leelawadee UI", 0, 14))); // NOI18N
        jPanel1.setMinimumSize(Toolkit.getDefaultToolkit().getScreenSize());
        jPanel1.setPreferredSize(Toolkit.getDefaultToolkit().getScreenSize());
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        jLabel1.setText("<html>Calibration<br>Agency Name</html>");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(40, 60, 130, 40);

        jTextField1.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        jPanel1.add(jTextField1);
        jTextField1.setBounds(170, 60, 213, 30);

        jLabel2.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        jLabel2.setText("Address:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(40, 100, 130, 30);

        jScrollPane1.setPreferredSize(new java.awt.Dimension(213, 100));

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(170, 110, 210, 80);

        jLabel3.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        jLabel3.setText("Contact No (LL)");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(40, 240, 130, 30);

        jLabel4.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        jLabel4.setText("Contact No (BOARD)");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(40, 280, 130, 30);

        jLabel5.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        jLabel5.setText("Weekly Off:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(40, 320, 130, 30);

        jComboBox1.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday" }));
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(170, 320, 213, 30);

        jTextField7.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        jPanel1.add(jTextField7);
        jTextField7.setBounds(170, 240, 213, 30);

        jTextField8.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        jPanel1.add(jTextField8);
        jTextField8.setBounds(170, 280, 213, 30);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Contact Person 1"));
        jPanel3.setLayout(null);

        jLabel8.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        jLabel8.setText("Contact No");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(20, 70, 130, 30);

        jLabel9.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        jLabel9.setText("Email");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(20, 110, 130, 30);

        jTextField9.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        jPanel3.add(jTextField9);
        jTextField9.setBounds(150, 70, 150, 30);

        jLabel19.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        jLabel19.setText("Name");
        jPanel3.add(jLabel19);
        jLabel19.setBounds(20, 30, 130, 30);

        jTextField10.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        jPanel3.add(jTextField10);
        jTextField10.setBounds(150, 110, 150, 30);

        jTextField4.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        jPanel3.add(jTextField4);
        jTextField4.setBounds(150, 30, 150, 30);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(450, 60, 340, 150);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Contact Person 3"));
        jPanel4.setLayout(null);

        jLabel10.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        jLabel10.setText("Contact No");
        jPanel4.add(jLabel10);
        jLabel10.setBounds(20, 70, 130, 30);

        jLabel11.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        jLabel11.setText("Email");
        jPanel4.add(jLabel11);
        jLabel11.setBounds(20, 110, 130, 30);

        jTextField11.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        jTextField11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField11ActionPerformed(evt);
            }
        });
        jPanel4.add(jTextField11);
        jTextField11.setBounds(150, 70, 150, 30);

        jTextField12.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        jPanel4.add(jTextField12);
        jTextField12.setBounds(150, 110, 150, 30);

        jLabel18.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        jLabel18.setText("Name");
        jPanel4.add(jLabel18);
        jLabel18.setBounds(20, 30, 130, 30);

        jTextField3.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        jPanel4.add(jTextField3);
        jTextField3.setBounds(150, 30, 150, 30);

        jPanel1.add(jPanel4);
        jPanel4.setBounds(450, 380, 340, 150);

        jLabel12.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        jLabel12.setText("GST No");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(40, 360, 130, 30);

        jTextField13.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        jTextField13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField13ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField13);
        jTextField13.setBounds(170, 360, 213, 30);

        jLabel13.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        jLabel13.setText("Our Vendor Code");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(40, 400, 130, 30);

        jTextField14.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        jTextField14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField14ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField14);
        jTextField14.setBounds(170, 400, 213, 30);

        jLabel14.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        jLabel14.setText("Payment Terms");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(40, 440, 130, 30);

        jButton1.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        jButton1.setText("Edit Record");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(1020, 550, 120, 30);

        jButton2.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        jButton2.setText("Add to Master");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(830, 550, 120, 30);

        jTable1.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable1);

        jPanel1.add(jScrollPane3);
        jScrollPane3.setBounds(830, 70, 310, 450);

        jButton3.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        jButton3.setText("Export to Excel");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(1020, 590, 120, 30);

        jLabel15.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        jLabel15.setText("Category");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(450, 550, 130, 30);

        jTextField15.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        jTextField15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField15ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField15);
        jTextField15.setBounds(570, 550, 213, 30);

        jLabel16.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        jLabel16.setText("Segment");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(450, 590, 130, 30);

        jTextField16.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        jPanel1.add(jTextField16);
        jTextField16.setBounds(570, 590, 213, 30);

        jLabel17.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        jLabel17.setText("Industry");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(450, 630, 130, 30);

        jTextField17.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        jPanel1.add(jTextField17);
        jTextField17.setBounds(570, 630, 213, 30);

        jLabel22.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        jLabel22.setText("City");
        jPanel1.add(jLabel22);
        jLabel22.setBounds(40, 200, 130, 30);

        jComboBox5.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mumbai", "Pune", "Nagpur", "Nashik", "Thane", "Pune", "Aurangabad", "Solapur", "Thane", "Palghar", "Thane", "Amravati", "Thane", "Akola", "Thane", "Dhule", "Jalgaon", "Nanded", "Kolhapur", "Latur", "Raigad", "Thane", "Sangli", "Nashik", "Ahmednagar", "Kolhapur", "Chandrapur", "Parbhani" }));
        jPanel1.add(jComboBox5);
        jComboBox5.setBounds(170, 200, 213, 30);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Contact Person 2"));
        jPanel6.setLayout(null);

        jLabel25.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        jLabel25.setText("Contact No");
        jPanel6.add(jLabel25);
        jLabel25.setBounds(20, 70, 130, 30);

        jLabel26.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        jLabel26.setText("Email");
        jPanel6.add(jLabel26);
        jLabel26.setBounds(20, 110, 130, 30);

        jTextField21.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        jPanel6.add(jTextField21);
        jTextField21.setBounds(150, 70, 150, 30);

        jLabel27.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        jLabel27.setText("Name");
        jPanel6.add(jLabel27);
        jLabel27.setBounds(20, 30, 130, 30);

        jTextField22.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        jPanel6.add(jTextField22);
        jTextField22.setBounds(150, 110, 150, 30);

        jTextField23.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        jPanel6.add(jTextField23);
        jTextField23.setBounds(150, 30, 150, 30);

        jPanel1.add(jPanel6);
        jPanel6.setBounds(450, 220, 340, 150);

        jLabel6.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        jLabel6.setText("Authorised For");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(40, 510, 130, 30);

        jComboBox2.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox2);
        jComboBox2.setBounds(170, 510, 213, 30);

        jTextField5.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        jPanel1.add(jTextField5);
        jTextField5.setBounds(170, 440, 213, 30);

        jButton4.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        jButton4.setText("Cancel");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(830, 590, 120, 30);

        jButton5.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        jButton5.setText("Reset");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(830, 630, 120, 30);

        jList1.setMaximumSize(new java.awt.Dimension(213, 100));
        jList1.setMinimumSize(new java.awt.Dimension(213, 100));
        jList1.setPreferredSize(new java.awt.Dimension(213, 100));
        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jList1);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(170, 550, 210, 110);

        add(jPanel1);
        jPanel1.setBounds(0, 0, 1210, 700);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        Calendar c2 = Calendar.getInstance();
        SimpleDateFormat sdf2 = new SimpleDateFormat("dd-MM-yyyy HH:mm:ss" );
        String strDate2 = sdf2.format(c2.getTime());
        
        int result;
        String success;
        String SUPP_NAME, SUPP_ADD, SUPP_CNT_LL, SUPP_CNT_BRD, WEEK_OFF, GST_NO, VENDOR_CODE, PAYT_TERMS, CITY, SEGMENT, INDUSTRY, CATEGORY, AUTHORIZED_RM, CREATED_ON, EDITED_ON, EDITED_BY;

        SUPP_NAME = jTextField1.getText();
        SUPP_ADD = jTextArea1.getText();
        SUPP_CNT_LL = jTextField7.getText();
        SUPP_CNT_BRD = jTextField8.getText();
        WEEK_OFF = jComboBox1.getSelectedItem().toString();
        GST_NO = jTextField13.getText();
        VENDOR_CODE = jTextField14.getText();
        PAYT_TERMS = jTextField5.getText();

        CITY = jComboBox5.getSelectedItem().toString();
        SEGMENT = jTextField16.getText();
        INDUSTRY = jTextField17.getText();
        CATEGORY = jTextField15.getText();

        AUTHORIZED_RM = "";
        int i = 0;
        while (i < rawMaterialModel.size()) {
            if (i == rawMaterialModel.size() - 1) {
                AUTHORIZED_RM = AUTHORIZED_RM + rawMaterialModel.get(i);
            } else {
                AUTHORIZED_RM = AUTHORIZED_RM + rawMaterialModel.get(i) + ",";
            }
            i++;
        }

        CREATED_ON = strDate2;
        EDITED_ON = strDate2;
        EDITED_BY = "EDITED_ON";

        result = DB_Operations.insertIntoSupplierMaster(SUPP_NAME, SUPP_ADD, SUPP_CNT_LL, SUPP_CNT_BRD, WEEK_OFF, GST_NO, VENDOR_CODE, PAYT_TERMS, CITY, SEGMENT, INDUSTRY, CATEGORY, AUTHORIZED_RM, CREATED_ON, EDITED_ON, EDITED_BY);

        String ContactPerson1_NAME = jTextField4.getText();
        String ContactPerson1_CONTACT_NO = jTextField9.getText();
        String ContactPerson1_EMAIL = jTextField10.getText();

        if (!ContactPerson1_NAME.equals("") || !ContactPerson1_CONTACT_NO.equals("") || !ContactPerson1_EMAIL.equals("")) {

            if (result != 0) {

                success = DB_Operations.insertIntoContactMaster(ContactPerson1_EMAIL, ContactPerson1_CONTACT_NO, 0, result, ContactPerson1_NAME, CREATED_ON, EDITED_ON, EDITED_BY);

                ContactPerson1_NAME = jTextField23.getText();
                ContactPerson1_CONTACT_NO = jTextField21.getText();
                ContactPerson1_EMAIL = jTextField22.getText();

                success = DB_Operations.insertIntoContactMaster(ContactPerson1_EMAIL, ContactPerson1_CONTACT_NO, 0, result, ContactPerson1_NAME, CREATED_ON, EDITED_ON, EDITED_BY);

                ContactPerson1_NAME = jTextField3.getText();
                ContactPerson1_CONTACT_NO = jTextField11.getText();
                ContactPerson1_EMAIL = jTextField12.getText();

                success = DB_Operations.insertIntoContactMaster(ContactPerson1_EMAIL, ContactPerson1_CONTACT_NO, 0, result, ContactPerson1_NAME, CREATED_ON, EDITED_ON, EDITED_BY);

            }

        } else {

        }

        JOptionPane.showMessageDialog(null, "" + result);

        resetFields();
        loadContent();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField11ActionPerformed

    private void jTextField15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField15ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Workbook wb = new HSSFWorkbook();

        ArrayList<String> column_names = new ArrayList<String>();
        ArrayList<String[]> values = new ArrayList<String[]>();
        int columnCount = 0;
        File file = null;
        try {
            ResultSet result = DB_Operations.getMasters("supplier");
            if (result != null) {
                ResultSetMetaData metaData = result.getMetaData();
                // names of columns
                columnCount = metaData.getColumnCount();
                for (int column = 2; column <= columnCount - 3; column++) {
                    column_names.add(metaData.getColumnName(column));
                }
            }
            // data of the table
            Vector<Vector<Object>> data = new Vector<Vector<Object>>();
            while (result.next()) {
                String[] val = new String[columnCount];
                for (int columnIndex = 2; columnIndex <= columnCount; columnIndex++) {
                    if (columnIndex < columnCount - 2) {
                        val[columnIndex - 2] = String.valueOf(result.getObject(columnIndex));
                    }
                }
                values.add(val);
            }
        } catch (SQLException e) {

        }

        // Cell style for header row
        CellStyle cs = wb.createCellStyle();
        //cs.setFillForegroundColor(HSSFColor.LIME.index);
        //cs.setFillPattern(HSSFCellStyle.SOLID_FOREGROUND);

        CellStyle cs2 = wb.createCellStyle();
        cs2.setFillForegroundColor(HSSFColor.ROSE.index);
        cs2.setFillPattern(HSSFCellStyle.SOLID_FOREGROUND);

        // New Sheet
        Sheet sheet1 = null;
        sheet1 = wb.createSheet("Supplier Master");
        sheet1.setColumnWidth(0, (15 * 500));

        Cell c = null;
        Cell c3 = null;

        Row row = sheet1.createRow(1);
        //  c = row.createCell(0);
        // c.setCellValue("");
        // c.setCellStyle(cs);

        int i = 1;
        //add column names to the firt row of excel
        row = sheet1.createRow(i++);
        for (int a = 0; a < column_names.size(); a++) {
            c = row.createCell(a);
            // c.setCellValue(cursor.getString(a));
            c.setCellValue(column_names.get(a));
            c.setCellStyle(cs);
        }

        for (int j = 0; j < values.size(); j++) {
            String[] rowValues = values.get(j);
            Row row4 = sheet1.createRow(i++);
            for (int k = 0; k < rowValues.length; k++) {
                {

                    c = row4.createCell(k);
                    c.setCellValue(rowValues[k]);
                    c.setCellStyle(cs);
                }
            }
            Calendar c2 = Calendar.getInstance();
            SimpleDateFormat sdf2 = new SimpleDateFormat("ddMMMyyyy_HH_mm_a");
            String strDate2 = sdf2.format(c2.getTime());
            file = new File("Supplier Master File " + strDate2 + ".xls");

            FileOutputStream os = null;

            try {
                os = new FileOutputStream(file);
                wb.write(os);
                wb.close();
                os.close();
                //JOptionPane.showMessageDialog(null, "New File generated at " + file.getAbsolutePath());
            } catch (IOException e) {
                JOptionPane.showMessageDialog(null, "Error " + e.getMessage());
            } finally {

            }

        }
        JOptionPane.showMessageDialog(null, "New File generated at " + file.getAbsolutePath());
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField14ActionPerformed

    private void jTextField13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField13ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:

        resetFields();


    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        HomeScreen3.home.removeForms();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:

        jButton2.setEnabled(false);

        resetFields();
        
        ArrayList<String> values = new ArrayList<String>();
        ArrayList<String> contactPersonArray = new ArrayList<String>();
        contactIDs = new int[3];

        int columnCount = 0;
        // get the model from the jtable
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

        // get the selected row index
        int selectedRowIndex = jTable1.getSelectedRow();
        // Integer.parseInt(model.getValueAt(selectedRowIndex, 0).toString() )
        //         JOptionPane.showMessageDialog(null, "" + model.getValueAt(selectedRowIndex, 0).toString() );
        try {
            ResultSet result = DB_Operations.getSingleMasters("supplier", Integer.parseInt(model.getValueAt(selectedRowIndex, 0).toString()));

            selectedEmpRecordId = Integer.parseInt(model.getValueAt(selectedRowIndex, 0).toString());

            if (result != null) {
                ResultSetMetaData metaData = result.getMetaData();

                columnCount = metaData.getColumnCount();

                while (result.next()) {

                    for (int columnIndex = 1; columnIndex <= columnCount; columnIndex++) {
                        if (columnIndex < columnCount - 2) {

                            values.add(String.valueOf(result.getObject(columnIndex)));
                        }
                    }
                }
            }

            result = DB_Operations.getSingleMasters("contact_person_supplier", selectedEmpRecordId);

            if (result != null) {
                ResultSetMetaData metaData = result.getMetaData();

                columnCount = metaData.getColumnCount();
                int i = 0;
                while (result.next()) {
                        contactIDs[i] = Integer.parseInt( String.valueOf(result.getObject(1))  );
                    i++;
                    for (int columnIndex = 1; columnIndex <= columnCount; columnIndex++) {

                        if (columnIndex < columnCount - 2) {

                            contactPersonArray.add(String.valueOf(result.getObject(columnIndex)));
                        }
                    }
                }
            }
        } catch (SQLException e) {

            System.out.println("Error " + e.getMessage());
        }

        jTextField1.setText(values.get(1));  //supplier namne
        jTextArea1.setText(values.get(2)); // address
        jTextField7.setText(values.get(3));   // contact ll
        jTextField8.setText(values.get(4)); //  contact board
        jComboBox1.setSelectedItem(0);   // 
        jTextField13.setText(values.get(6)); //weekly off
        jTextField5.setText(values.get(9)); // payment terms
        jComboBox5.getSelectedItem().toString(); // city
        jTextField16.setText(values.get(11));  // segment 
        jTextField17.setText(values.get(10));  // industry
        jTextField15.setText(values.get(8));  // category
        jTextField14.setText(values.get(7));  // category
        jComboBox5.setSelectedItem(0);  // supplier authorized for raw material

        String[] RMListString = values.get(13).split(",");
        rawMaterialModel.removeAllElements();
        for (int i = 0; i < RMListString.length; i++) {
            rawMaterialModel.addElement(RMListString[i]);
        }
        jList1.setModel(rawMaterialModel);

        try {
            jTextField4.setText(contactPersonArray.get(5));
            jTextField9.setText(contactPersonArray.get(2));
            jTextField10.setText(contactPersonArray.get(1));

        } catch (ArrayIndexOutOfBoundsException r) {

        } catch (IndexOutOfBoundsException e) {

        }

        try {

            jTextField23.setText(contactPersonArray.get(11));
            jTextField21.setText(contactPersonArray.get(8));
            jTextField22.setText(contactPersonArray.get(7));

        } catch (ArrayIndexOutOfBoundsException r) {

        } catch (IndexOutOfBoundsException e) {

        }

        try {

            jTextField3.setText(contactPersonArray.get(17));
            jTextField11.setText(contactPersonArray.get(14));
            jTextField12.setText(contactPersonArray.get(13));
        } catch (ArrayIndexOutOfBoundsException r) {

        } catch (IndexOutOfBoundsException e) {

        }

        jButton1.setEnabled(true);


    }//GEN-LAST:event_jTable1MouseClicked

    DefaultListModel<String> rawMaterialModel = new DefaultListModel();
    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:

        if (!rawMaterialModel.contains(jComboBox2.getSelectedItem().toString())) {
            rawMaterialModel.addElement(jComboBox2.getSelectedItem().toString());
            jList1.setModel(rawMaterialModel);
        }
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String SUPP_NAME, SUPP_ADD, SUPP_CNT_LL, SUPP_CNT_BRD, WEEK_OFF, GST_NO, VENDOR_CODE, PAYT_TERMS, CITY, SEGMENT, INDUSTRY, CATEGORY, AUTHORIZED_RM, EDITED_ON, EDITED_BY;

        SUPP_NAME = jTextField1.getText();
        SUPP_ADD = jTextArea1.getText();
        SUPP_CNT_LL = jTextField7.getText();
        SUPP_CNT_BRD = jTextField8.getText();
        WEEK_OFF = jComboBox1.getSelectedItem().toString();
        GST_NO = jTextField13.getText();
        VENDOR_CODE = jTextField14.getText();
        PAYT_TERMS = jTextField5.getText();
        CITY = jComboBox5.getSelectedItem().toString();
        SEGMENT = jTextField16.getText();
        INDUSTRY = jTextField17.getText();
        CATEGORY = jTextField15.getText();

        AUTHORIZED_RM = "";
        int i = 0;
        while (i < rawMaterialModel.size()) {
            if (i == rawMaterialModel.size() - 1) {
                AUTHORIZED_RM = AUTHORIZED_RM + rawMaterialModel.get(i);
            } else {
                AUTHORIZED_RM = AUTHORIZED_RM + rawMaterialModel.get(i) + ",";
            }
            i++;
        }

        EDITED_ON = "EDITED_BY";
        EDITED_BY = "EDITED_ON";

        int ID = selectedEmpRecordId;

        String result = DB_Operations.updateSuppliersMaster(SUPP_NAME, SUPP_ADD, SUPP_CNT_LL, SUPP_CNT_BRD, WEEK_OFF, GST_NO, VENDOR_CODE, PAYT_TERMS, CITY, SEGMENT, INDUSTRY, CATEGORY, AUTHORIZED_RM, EDITED_ON, EDITED_BY, ID);

        String ContactPerson1_NAME = jTextField4.getText();
        String ContactPerson1_CONTACT_NO = jTextField9.getText();
        String ContactPerson1_EMAIL = jTextField10.getText();
        DB_Operations.updateContactMaster(ContactPerson1_EMAIL, ContactPerson1_CONTACT_NO, ContactPerson1_NAME, 0, selectedEmpRecordId, contactIDs[0]);
     
                                                                                                                                                        

        ContactPerson1_NAME = jTextField23.getText();
        ContactPerson1_CONTACT_NO = jTextField21.getText();
        ContactPerson1_EMAIL = jTextField22.getText();
        DB_Operations.updateContactMaster(ContactPerson1_EMAIL, ContactPerson1_CONTACT_NO, ContactPerson1_NAME, 0, selectedEmpRecordId, contactIDs[1]);

        ContactPerson1_NAME = jTextField3.getText();
        ContactPerson1_CONTACT_NO = jTextField11.getText();
        ContactPerson1_EMAIL = jTextField12.getText();
        DB_Operations.updateContactMaster(ContactPerson1_EMAIL, ContactPerson1_CONTACT_NO, ContactPerson1_NAME, 0, selectedEmpRecordId, contactIDs[2]);

        JOptionPane.showMessageDialog(null, "" + result);

        resetFields();
        loadContent();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
        // TODO add your handling code here:
        int selection = jList1.getSelectedIndex();
        rawMaterialModel.removeElementAt(selection);
        jList1.setModel(rawMaterialModel);
    }//GEN-LAST:event_jList1MouseClicked

    public void resetFields() {

        jTextField1.setText("");
        jTextArea1.setText("");
        jTextField7.setText("");
        jTextField8.setText("");
        jComboBox1.getSelectedItem().toString();
        jTextField13.setText("");
        jTextField14.setText("");
        jTextField5.setText("");

        jComboBox5.getSelectedItem().toString();
        jTextField16.setText("");
        jTextField17.setText("");
        jTextField15.setText("");

        rawMaterialModel.removeAllElements();
        jList1.setModel(rawMaterialModel);

       
            jTextField4.setText( "" );
            jTextField9.setText( "" );
            jTextField10.setText( "" );
            jTextField23.setText( "" );
            jTextField21.setText( "" );
            jTextField22.setText( "" );
            jTextField3.setText( "" );
            jTextField11.setText( "" );
            jTextField12.setText( "" );
       
        
        
        jButton2.setEnabled(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JTextField jTextField23;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables

    int selectedEmpRecordId = 0;
    int contactIDs[] = new int[]{0, 0, 0};
}
