/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trixware.erp.prodezydesktop.examples;
import static trixware.erp.prodezydesktop.examples.GraphsWidget.dataSet;
import java.awt.Color;
import java.awt.Font;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.axis.CategoryAxis;
import org.jfree.chart.axis.CategoryLabelPositions;
import org.jfree.chart.labels.StandardCategoryItemLabelGenerator;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.plot.ValueMarker;
import org.jfree.chart.renderer.category.BarRenderer;
import org.jfree.chart.renderer.category.LineRenderer3D;
import org.jfree.chart.renderer.category.StandardBarPainter;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.ui.TextAnchor;

/**
 *
 * @author Rajesh
 */
public class CommonGraphPanel1 extends javax.swing.JPanel {

    public JFreeChart chart = null;
    public static DefaultCategoryDataset dataSet = null;
    static ChartPanel cp = null;
    
    int xCod = 0, yCod = 0 ;
    
    /**
     * Creates new form CommonGraphPanel
     */
    public CommonGraphPanel1 (  String graphTitle, String xAxis, String yAxis   ) {
        initComponents ();
        
        dataSet = new DefaultCategoryDataset ();
        for ( int i = 0 ; i < 30 ; i ++ ) {
            dataSet.setValue ( i , "" , String.valueOf ( i ) );
        }
        
       /* chart = ChartFactory.createBarChart3D (
                graphTitle , xAxis , yAxis ,
                dataSet , PlotOrientation.VERTICAL , true , true , false );*/
        
       chart = ChartFactory.createBarChart (
                graphTitle , xAxis , yAxis ,
                dataSet , PlotOrientation.VERTICAL , false , true , false );
        
        
        
        chart.getTitle().setFont ( new Font ( "Times New Roman" , Font.PLAIN , 10 ) );
    }

    public ChartPanel getPreparedCP(){
        
        
        
        cp = new ChartPanel ( chart );
        cp.setPreferredSize ( new java.awt.Dimension ( 300 , 200 ) );
        cp.setBackground ( Color.WHITE );
        
        //CategoryPlot plot = ( CategoryPlot ) chart.getPlot ();
        CategoryPlot plot = (CategoryPlot)chart.getPlot() ;
        plot.setBackgroundPaint ( Color.WHITE );
        plot.setDomainGridlinePaint ( Color.white );
        plot.setDomainGridlinesVisible ( false );
        plot.setRangeGridlinePaint ( Color.white );
        plot.setOutlinePaint(null);
        plot.getDomainAxis().setLabelFont(new Font ( "Times New Roman" , Font.PLAIN , 10 ));
        plot.getDomainAxis().setTickLabelFont ( new Font ( "Times New Roman" , Font.PLAIN , 10 ));
        plot.getRangeAxis().setLabelFont(new Font ( "Times New Roman" , Font.PLAIN , 10 ));
        plot.getRangeAxis().setTickLabelFont ( new Font ( "Times New Roman" , Font.PLAIN , 10 ));
       
        CategoryAxis domainAxis = plot.getDomainAxis ();
        domainAxis.setCategoryLabelPositions ( CategoryLabelPositions.DOWN_45 );
        BarRenderer renderer = ( BarRenderer ) plot.getRenderer ();
        renderer.setBaseItemLabelsVisible ( true );
        renderer.setBaseItemLabelGenerator ( new StandardCategoryItemLabelGenerator () );
        renderer.setSeriesPaint ( 0 , new Color(127,211,101) );
        renderer.setBarPainter(new StandardBarPainter());
        renderer.setSeriesItemLabelFont ( 0 , new Font ( "Times New Roman" , Font.PLAIN , 8 ) );
        renderer.setSeriesItemLabelPaint ( 0 , Color.BLACK );
        
        
        return cp ;
    }
   
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings( "unchecked" )
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
