/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trixware.erp.prodezydesktop.examples;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;
import trixware.erp.prodezydesktop.Model.Proman_User;
import trixware.erp.prodezydesktop.Utilities.LoginDialog;
import trixware.erp.prodezydesktop.masters.Calibration;
import trixware.erp.prodezydesktop.masters.CustomerMaster;
import trixware.erp.prodezydesktop.masters.Employee_HR_Master;
import trixware.erp.prodezydesktop.masters.FinishedGoodMaster_old;
import trixware.erp.prodezydesktop.masters.MachineMaster;
import trixware.erp.prodezydesktop.masters.Process_Master_Form;
import trixware.erp.prodezydesktop.masters.Processforfinishedgoods;
import trixware.erp.prodezydesktop.masters.Raw_Material;
import trixware.erp.prodezydesktop.masters.SupplierMaster;
import trixware.erp.prodezydesktop.masters.TestingMaster;
import trixware.erp.prodezydesktop.masters.UtilitiyMasters;

/**
 *
 * @author Rajesh
 */
public class HomeScreen3 extends javax.swing.JFrame {

    public LoginDialog loginDlg = new LoginDialog(HomeScreen3.this);

    /**
     * Creates new form HomeScreen
     */
    public HomeScreen3() {
        initComponents();

        //   Proman_User.setUsername("");
        //  Proman_User.setPassword("");
        //  Proman_User.setIsActivelyLoggedIn(false);
    }

    static JPanel parentPanel;
    public static HomeScreen3 home;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenuItem18 = new javax.swing.JMenuItem();
        jMenuItem20 = new javax.swing.JMenuItem();
        jMenuItem23 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem19 = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem21 = new javax.swing.JMenuItem();
        jMenuItem22 = new javax.swing.JMenuItem();
        jMenuItem24 = new javax.swing.JMenuItem();

        jMenu3.setText("jMenu3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(87, 102, 226));
        setMaximumSize(Toolkit.getDefaultToolkit().getScreenSize());
        setMinimumSize(new java.awt.Dimension(1366, 730));
        setPreferredSize(Toolkit.getDefaultToolkit().getScreenSize());
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });
        getContentPane().setLayout(null);

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(null);
        jScrollPane1.setForeground(new java.awt.Color(25, 147, 209));
        jScrollPane1.setMaximumSize(Toolkit.getDefaultToolkit().getScreenSize());
        jScrollPane1.setMinimumSize(new java.awt.Dimension(1366, 660));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(1366, 660));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(25, 147, 209));
        jPanel1.setMaximumSize(Toolkit.getDefaultToolkit().getScreenSize());
        jPanel1.setMinimumSize(new java.awt.Dimension(1350, 650));
        jPanel1.setPreferredSize(new java.awt.Dimension(1350, 650));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Leelawadee UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("<html> Production   Manager Lite <br> V 0.1.1 </html>  ");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(600, 540, 500, 100);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Utilities/assets/Shop-Floor-Control.jpg"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 900, 546);

        jScrollPane1.setViewportView(jPanel1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 25, 1366, 660);
        jScrollPane1.getAccessibleContext().setAccessibleName("");

        jLabel3.setBackground(new java.awt.Color(51, 153, 255));
        jLabel3.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(787, 6, 160, 16);

        jLabel4.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(959, 6, 155, 16);

        jMenuBar1.setBackground(new java.awt.Color(51, 153, 255));
        jMenuBar1.setForeground(new java.awt.Color(51, 153, 255));
        jMenuBar1.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N

        jMenu1.setText("File");
        jMenu1.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
        jMenu1.setMargin(new java.awt.Insets(3, 3, 3, 0));

        jMenu4.setText("Masters");
        jMenu4.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
        jMenu4.setMargin(new java.awt.Insets(5, 5, 5, 0));

        jMenuItem2.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
        jMenuItem2.setText("Customer");
        jMenuItem2.setMargin(new java.awt.Insets(5, 5, 5, 0));
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem2);

        jMenuItem3.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
        jMenuItem3.setText("Supplier");
        jMenuItem3.setMargin(new java.awt.Insets(5, 5, 5, 0));
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem3);

        jMenuItem4.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
        jMenuItem4.setText("Machines");
        jMenuItem4.setMargin(new java.awt.Insets(5, 5, 5, 0));
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem4);

        jMenuItem6.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
        jMenuItem6.setText("Raw Material");
        jMenuItem6.setMargin(new java.awt.Insets(5, 5, 5, 0));
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem6);

        jMenuItem8.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
        jMenuItem8.setText("Finished Goods");
        jMenuItem8.setMargin(new java.awt.Insets(5, 5, 5, 0));
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem8);

        jMenuItem9.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
        jMenuItem9.setText("Testing Master");
        jMenuItem9.setMargin(new java.awt.Insets(5, 5, 5, 0));
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem9);

        jMenuItem10.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
        jMenuItem10.setText("Employee Master");
        jMenuItem10.setMargin(new java.awt.Insets(5, 5, 5, 0));
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem10);

        jMenuItem7.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
        jMenuItem7.setText("Calibration");
        jMenuItem7.setMargin(new java.awt.Insets(5, 5, 5, 0));
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem7);

        jMenuItem1.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
        jMenuItem1.setText("Utility Masters");
        jMenuItem1.setMargin(new java.awt.Insets(5, 5, 5, 0));
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem1);

        jMenuItem17.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
        jMenuItem17.setText("Process Master");
        jMenuItem17.setMargin(new java.awt.Insets(3, 3, 3, 0));
        jMenuItem17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem17ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem17);

        jMenu1.add(jMenu4);

        jMenu5.setText("Inventory");
        jMenu5.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
        jMenu5.setMargin(new java.awt.Insets(5, 5, 5, 2));

        jMenuItem5.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
        jMenuItem5.setText("Update");
        jMenuItem5.setMargin(new java.awt.Insets(3, 3, 3, 0));
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem5);

        jMenuItem11.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
        jMenuItem11.setText("View");
        jMenuItem11.setMargin(new java.awt.Insets(3, 3, 3, 0));
        jMenu5.add(jMenuItem11);

        jMenu1.add(jMenu5);

        jMenu7.setText("Operations");
        jMenu7.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
        jMenu7.setMargin(new java.awt.Insets(5, 5, 5, 2));

        jMenuItem13.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
        jMenuItem13.setText("Production");
        jMenuItem13.setMargin(new java.awt.Insets(3, 3, 3, 0));
        jMenu7.add(jMenuItem13);

        jMenuItem14.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
        jMenuItem14.setText("Sales");
        jMenuItem14.setMargin(new java.awt.Insets(3, 3, 3, 0));
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem14);

        jMenuItem15.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
        jMenuItem15.setText("Work In Progress");
        jMenuItem15.setMargin(new java.awt.Insets(3, 3, 3, 0));
        jMenuItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem15ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem15);

        jMenuItem18.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
        jMenuItem18.setText("Process Map");
        jMenuItem18.setMargin(new java.awt.Insets(3, 3, 3, 0));
        jMenuItem18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem18ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem18);

        jMenuItem20.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
        jMenuItem20.setText("Daily Report 2");
        jMenuItem20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem20MouseClicked(evt);
            }
        });
        jMenuItem20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem20ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem20);

        jMenuItem23.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
        jMenuItem23.setText("Daily Report");
        jMenuItem23.setMargin(new java.awt.Insets(3, 3, 3, 2));
        jMenuItem23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem23MouseClicked(evt);
            }
        });
        jMenuItem23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem23ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem23);

        jMenu1.add(jMenu7);

        jMenuBar1.add(jMenu1);

        jMenu2.setBackground(new java.awt.Color(102, 153, 255));
        jMenu2.setForeground(new java.awt.Color(51, 153, 255));
        jMenu2.setText("Utilities");
        jMenu2.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        jMenuItem12.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
        jMenuItem12.setText("Widgets");
        jMenuItem12.setMargin(new java.awt.Insets(3, 3, 3, 0));
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem12);

        jMenuItem19.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
        jMenuItem19.setText("Sales Report");
        jMenuItem19.setMargin(new java.awt.Insets(3, 3, 3, 0));
        jMenuItem19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem19ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem19);

        jMenuItem16.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
        jMenuItem16.setText("Logout");
        jMenuItem16.setMargin(new java.awt.Insets(3, 3, 3, 0));
        jMenuItem16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem16ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem16);

        jMenu6.setText("Report");
        jMenu6.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
        jMenu6.setMargin(new java.awt.Insets(3, 3, 3, 0));

        jMenuItem21.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
        jMenuItem21.setText("Production");
        jMenuItem21.setMargin(new java.awt.Insets(3, 3, 3, 0));
        jMenuItem21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem21ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem21);

        jMenuItem22.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
        jMenuItem22.setText("WIP");
        jMenuItem22.setMargin(new java.awt.Insets(3, 3, 3, 0));
        jMenuItem22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem22ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem22);

        jMenuItem24.setText("WIP 2");
        jMenuItem24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem24MouseClicked(evt);
            }
        });
        jMenuItem24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem24ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem24);

        jMenu2.add(jMenu6);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        getAccessibleContext().setAccessibleName("homeFrame");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void removeForms() {
        home.jPanel1.removeAll();
        home.jPanel1.add(jLabel1);
        home.jPanel1.add(jLabel2);
        home.jPanel1.setLayout(null);
        home.revalidate();
        home.repaint();

        System.gc();
    }
    
     public static void LoadDashboard() {
        home.jPanel1.removeAll();
        home.jPanel1.setLayout(null);
        home.revalidate();
        home.repaint();

         InventoryWidget1 ant = new InventoryWidget1();
        ant.setBounds(0, 0, home.jPanel1.getWidth(), home.jPanel1.getHeight());
       
        home.jPanel1.removeAll();
        home.jPanel1.setLayout(null);
        home.jPanel1.add(ant);
        home.revalidate();
        home.repaint();
        
        
        //    System.gc();
    }

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:

        if (Proman_User.isActivelyLoggedIn()) {

            showCustomerScreen();
        } else if (showLogin()) {

            showCustomerScreen();
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void showCustomerScreen() {

        CustomerMaster customer = new CustomerMaster();
        customer.setBounds(0, 0, home.jPanel1.getWidth(), home.jPanel1.getHeight());
        customer.loadContent();
        home.jPanel1.removeAll();
        home.jPanel1.setLayout(null);
        home.jPanel1.add(customer);
        home.revalidate();
        home.repaint();

        //     JOptionPane.showMessageDialog(null, "Please enter valid text"  );
    }

    private void showSupplierScreen() {

        SupplierMaster supplier = new SupplierMaster();
        supplier.setBounds(0, 0, home.jPanel1.getWidth(), home.jPanel1.getHeight());
        supplier.loadContent();
        home.jPanel1.removeAll();
        home.jPanel1.setLayout(null);
        home.jPanel1.add(supplier);
        home.revalidate();
        home.repaint();
    }

    private void showEmployeeScreen() {

        Employee_HR_Master emplHRMaster = new Employee_HR_Master();
        emplHRMaster.setBounds(0, 0, home.jPanel1.getWidth(), home.jPanel1.getHeight());
        emplHRMaster.loadContent();
        home.jPanel1.removeAll();
        home.jPanel1.setLayout(null);
        home.jPanel1.add(emplHRMaster);
        home.revalidate();
        home.repaint();
    }

    private void showMachineScreen() {

        MachineMaster machine = new MachineMaster();
        machine.setBounds(0, 0, home.jPanel1.getWidth(), home.jPanel1.getHeight());
        machine.loadContent();
        home.jPanel1.removeAll();
        home.jPanel1.setLayout(null);
        home.jPanel1.add(machine, BorderLayout.CENTER);
        home.pack();
        home.revalidate();
        home.repaint();
    }

    private void showRawMaterialScreen() {

        Raw_Material rawM = new Raw_Material();
        rawM.setBounds(0, 0, home.jPanel1.getWidth(), home.jPanel1.getHeight());
        
        
         Dimension d = Toolkit.getDefaultToolkit().getScreenSize();
        int screenW = (int) d.getWidth();
        int paneW = 850;
       
        System.out.println(screenW + " "+paneW+" " ); 
        
        rawM.setBounds((int)((screenW-paneW)/2), 20, paneW, 480);
        
        
        rawM.loadContent();
        home.jPanel1.removeAll();
        home.jPanel1.setLayout(null);
        home.jPanel1.add(rawM);
        home.revalidate();
        home.repaint();

    }

    private void showUtilitiesScreen() {

        UtilitiyMasters utilities = new UtilitiyMasters();
        utilities.setBounds(0, 0, home.jPanel1.getWidth(), home.jPanel1.getHeight());
        //  utilities.getRootPane().setDefaultButton( utilities.  );
        utilities.loadContent("grade");
        home.jPanel1.removeAll();
        home.jPanel1.setLayout(null);
        home.jPanel1.add(utilities);
        home.revalidate();
        home.repaint();
    }

    private void showTestingScreen() {

        TestingMaster testingM = new TestingMaster();
        testingM.setBounds(0, 0, home.jPanel1.getWidth(), home.jPanel1.getHeight());
        testingM.loadContent();
        home.jPanel1.removeAll();
        home.jPanel1.setLayout(null);
        home.jPanel1.add(testingM);
        home.revalidate();
        home.repaint();
    }

    private void showCalibrationScreen() {

        Calibration calibration = new Calibration();
        calibration.setBounds(0, 0, home.jPanel1.getWidth(), home.jPanel1.getHeight());
        calibration.loadContent();
        home.jPanel1.removeAll();
        home.jPanel1.setLayout(null);
        home.jPanel1.add(calibration);
        home.revalidate();
        home.repaint();
    }

    private void showFinishedGoodsScreen() {

        FinishedGoodMaster_old finishedGoods = new FinishedGoodMaster_old();
        finishedGoods.setBounds(0, 0, home.jPanel1.getWidth(), home.jPanel1.getHeight());

        finishedGoods.loadContent();
        home.jPanel1.removeAll();
        home.jPanel1.setLayout(null);
        home.jPanel1.add(finishedGoods);
        home.revalidate();
        home.repaint();
    }

    public boolean showLogin() {

        loginDlg.setVisible(true);
        // if logon successfully
        if (loginDlg.isSucceeded()) {
            Proman_User.setUsername("");
            Proman_User.setPassword("");
            Proman_User.setIsActivelyLoggedIn(true);

            return true;
        } else {
            return false;
        }
    }

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:

        if (Proman_User.isActivelyLoggedIn()) {

            showSupplierScreen();
        } else if (Proman_User.isActivelyLoggedIn()) {

            showSupplierScreen();
        }
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:

        if (Proman_User.isActivelyLoggedIn()) {

            showMachineScreen();
        } else if (showLogin()) {

            showMachineScreen();
        }
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:

        if (Proman_User.isActivelyLoggedIn()) {

            showRawMaterialScreen();
        } else if (showLogin()) {

            showRawMaterialScreen();
        }
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:

        if (Proman_User.isActivelyLoggedIn()) {

            showFinishedGoodsScreen();
        } else if (showLogin()) {

            showFinishedGoodsScreen();
        }
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:

        if (Proman_User.isActivelyLoggedIn()) {

            showTestingScreen();
        } else if (showLogin()) {

            showTestingScreen();
        }
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        // TODO add your handling code here:

        if (Proman_User.isActivelyLoggedIn()) {

            showEmployeeScreen();
        } else if (showLogin()) {

            showEmployeeScreen();
        }

    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:

        if (Proman_User.isActivelyLoggedIn()) {

            showCalibrationScreen();
        } else if (showLogin()) {

            showCalibrationScreen();
        }

    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:

        if (Proman_User.isActivelyLoggedIn()) {

            showUtilitiesScreen();
        } else if (showLogin()) {

            showUtilitiesScreen();
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:

        UpdateStockPanel updateStockRM = new UpdateStockPanel();
        Dimension d = Toolkit.getDefaultToolkit().getScreenSize();
        int screenW = (int) d.getWidth();
        int paneW = 550;
       
        System.out.println(screenW + " "+paneW+" " ); 
        
        updateStockRM.setBounds((int)((screenW-paneW)/2), 20, paneW, paneW);

        updateStockRM.loadContent();
        home.jPanel1.removeAll();
        home.jPanel1.setLayout(null);
        home.jPanel1.add(updateStockRM);
        home.revalidate();
        home.repaint();

    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem15ActionPerformed
        // TODO add your handling code here:
        WIP_Operationsv4 finishedGoods = new WIP_Operationsv4();
        finishedGoods.setBounds(0, 0, home.jPanel1.getWidth(), home.jPanel1.getHeight());

        home.jPanel1.removeAll();
        home.jPanel1.setLayout(null);
        home.jPanel1.add(finishedGoods);
        home.revalidate();
        home.repaint();
    }//GEN-LAST:event_jMenuItem15ActionPerformed

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed
        // TODO add your handling code here:
        
        SalesForm salesForm = new SalesForm();
        salesForm.setBounds(0, 0, home.jPanel1.getWidth(), home.jPanel1.getHeight());
        
        home.jPanel1.removeAll();
        home.jPanel1.setLayout(null);
        home.jPanel1.add(salesForm);
        home.revalidate();
        home.repaint();
    }//GEN-LAST:event_jMenuItem14ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        // TODO add your handling code here:
        if (Proman_User.isActivelyLoggedIn()) {
            LoadDashboard ();
        } else if (showLogin()) {
            LoadDashboard ();
        }
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenuItem16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem16ActionPerformed
        // TODO add your handling code here:
          Proman_User.setUsername("");
          Proman_User.setPassword("");
          Proman_User.setIsActivelyLoggedIn(false);       
          removeForms();
    }//GEN-LAST:event_jMenuItem16ActionPerformed

    private void jMenuItem17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem17ActionPerformed
        // TODO add your handling code here:
        Process_Master_Form process = new Process_Master_Form ();
        Dimension d = Toolkit.getDefaultToolkit().getScreenSize();
        int screenW = (int) d.getWidth();
        int paneW = 650;
        
        process.setBounds( (int)((screenW-paneW)/2), 20, paneW, 400);
        
        home.jPanel1.removeAll();
        home.jPanel1.setLayout(null);
        home.jPanel1.add(process);
        home.revalidate();
        home.repaint();
    }//GEN-LAST:event_jMenuItem17ActionPerformed

    private void jMenuItem18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem18ActionPerformed
        // TODO add your handling code here:
        Processforfinishedgoods process = new Processforfinishedgoods ();
        Dimension d = Toolkit.getDefaultToolkit().getScreenSize();
        int screenW = (int) d.getWidth();
        int paneW = 680;
        
        process.setBounds( (int)((screenW-paneW)/2), 20, paneW, 520);
        
        home.jPanel1.removeAll();
        home.jPanel1.setLayout(null);
        home.jPanel1.add(process);
        home.revalidate();
        home.repaint();
    }//GEN-LAST:event_jMenuItem18ActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        // TODO add your handling code here:
        
       
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void jMenuItem19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem19ActionPerformed
        // TODO add your handling code here:
         System.out.println( "Opening Reports " );
        
        SalesReports process = new SalesReports ();
        Dimension d = Toolkit.getDefaultToolkit().getScreenSize();
        int screenW = (int) d.getWidth();
        int paneW = 680;
        
        process.setBounds( (int)((screenW-paneW)/2), 20, 800, 600);
        
        home.jPanel1.removeAll();
        home.jPanel1.setLayout(null);
        home.jPanel1.add(process);
        home.revalidate();
        home.repaint();
    }//GEN-LAST:event_jMenuItem19ActionPerformed

    private void jMenuItem20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem20MouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jMenuItem20MouseClicked

    private void jMenuItem20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem20ActionPerformed
        // TODO add your handling code here:
        DailyReportForm2 process = new DailyReportForm2 ();
        Dimension d = Toolkit.getDefaultToolkit().getScreenSize();
        int screenW = (int) d.getWidth();
        int screenH = (int) d.getHeight();
        int paneW = screenW;
        
        process.setBounds( 0, 0, paneW, screenH-100);
        
        home.jPanel1.removeAll();
        home.jPanel1.setLayout(null);
        home.jPanel1.add(process);
        home.revalidate();
        home.repaint();
        
    //    System.out.println("Cannot load daily report");
    }//GEN-LAST:event_jMenuItem20ActionPerformed

    private void jMenuItem21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem21ActionPerformed
        // TODO add your handling code here:
        ProductionNWIP2 process = new ProductionNWIP2 ();
        Dimension d = Toolkit.getDefaultToolkit().getScreenSize();
        int screenW = (int) d.getWidth();
        int screenH = (int) d.getHeight();
        int paneW = screenW;
        
        process.setBounds( 0, 0, paneW, screenH);
       
        home.jPanel1.removeAll();
        home.jPanel1.setLayout(null);
        home.jPanel1.add(process);
        home.revalidate();
        home.repaint();
    }//GEN-LAST:event_jMenuItem21ActionPerformed

    private void jMenuItem22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem22ActionPerformed
        // TODO add your handling code here:
       // ProductionNWIP1 process = new ProductionNWIP1 ();
        ReportWIP1 process = new ReportWIP1();
        Dimension d = Toolkit.getDefaultToolkit().getScreenSize();
        int screenW = (int) d.getWidth();
        int screenH = (int) d.getHeight();
        int paneW = 1035;
        
        process.setBounds( 0, 0, screenW, screenH-100);
        
        home.jPanel1.removeAll();
        home.jPanel1.setLayout(null);
        home.jPanel1.add(process);
        home.revalidate();
        home.repaint();
    }//GEN-LAST:event_jMenuItem22ActionPerformed

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
        // TODO add your handling code here:
    }//GEN-LAST:event_formComponentResized

    private void jMenuItem23MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem23MouseClicked
        // TODO add your handling code here:
       
        
    }//GEN-LAST:event_jMenuItem23MouseClicked

    private void jMenuItem23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem23ActionPerformed
        // TODO add your handling code here:
         DailyReportForm process = new DailyReportForm ();
        Dimension d = Toolkit.getDefaultToolkit().getScreenSize();
        int screenW = (int) d.getWidth();
        int screenH = (int) d.getHeight();
        int paneW = screenW;
        
        process.setBounds( 0, 0, paneW, screenH-100);
        
        home.jPanel1.removeAll();
        home.jPanel1.setLayout(null);
        home.jPanel1.add(process);
        home.revalidate();
        home.repaint();
    }//GEN-LAST:event_jMenuItem23ActionPerformed

    private void jMenuItem24MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem24MouseClicked
        // TODO add your handling code here:
         
    }//GEN-LAST:event_jMenuItem24MouseClicked

    private void jMenuItem24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem24ActionPerformed
        // TODO add your handling code here:
        ReportWIP2 process = new ReportWIP2();
        Dimension d = Toolkit.getDefaultToolkit().getScreenSize();
        int screenW = (int) d.getWidth();
        int screenH = (int) d.getHeight();
        int paneW = 1035;
        
        process.setBounds( 0, 0, screenW, screenH-100);
        
        home.jPanel1.removeAll();
        home.jPanel1.setLayout(null);
        home.jPanel1.add(process);
        home.revalidate();
        home.repaint();
    }//GEN-LAST:event_jMenuItem24ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeScreen3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeScreen3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeScreen3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeScreen3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                home = new HomeScreen3();
                home.setVisible(true);
                home.setTitle("Production Manager V-0.1.2");
                home.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N;

                home.jLabel3.setText( "Welcome Guest !!" );
                
                                Dimension d = Toolkit.getDefaultToolkit().getScreenSize();
                                int screenW = (int) d.getWidth();
                                jLabel2.setBounds((int)((screenW-900)/2), 20, 900, 546);
                                
                                jLabel1.setBounds ( (int)((screenW)/2), 546, 500, 100);
                
                                Thread t = new Thread() {
                                    public void run() {
                                        while (true) {
                                            try {
                                                c2 = Calendar.getInstance();
                                                sdf2 = new SimpleDateFormat("dd MMM yyyy -  HH : mm : ss a");
                                                String strDate2 = sdf2.format(c2.getTime());
                                                Thread.sleep(1000);
                                                home.jLabel4.setText( strDate2);

                                            } catch (InterruptedException ex) {
                                                Logger.getLogger(HomeScreen3.class.getName()).log(Level.SEVERE, null, ex);
                                            }
                                        }
                                    }
                                };

                                t.start();

             //   if (!Proman_User.isActivelyLoggedIn()) {
             //       home.showLogin();
            //    }else{
            //        home.remove( home.jLabel1 );
             //       home.remove( home.jLabel2 );
             //   }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JLabel jLabel1;
    private static javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem20;
    private javax.swing.JMenuItem jMenuItem21;
    private javax.swing.JMenuItem jMenuItem22;
    private javax.swing.JMenuItem jMenuItem23;
    private javax.swing.JMenuItem jMenuItem24;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    static Calendar c2 ;
    static SimpleDateFormat sdf2 ;
}



/*
 * 
 * 
                
 * 
 * 
 */