/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trixware.erp.prodezydesktop.examples;

/**
 *
 * @author dell(mayur)
 */
public class SingleHourDE_LabelsHours extends javax.swing.JPanel {

    /**
     * Creates new form SingleHourDE_Form
     * This form is labels of hourly entry form 
     */
    public SingleHourDE_LabelsHours () {
        initComponents ();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings( "unchecked" )
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        setOpaque(false);
        setLayout(null);

        jLabel7.setFont(new java.awt.Font("Leelawadee UI", 0, 10)); // NOI18N
        jLabel7.setText("No of Operator");
        add(jLabel7);
        jLabel7.setBounds(360, 0, 80, 30);

        jLabel9.setFont(new java.awt.Font("Leelawadee UI", 0, 10)); // NOI18N
        jLabel9.setText("Time");
        add(jLabel9);
        jLabel9.setBounds(20, 0, 70, 30);

        jLabel11.setFont(new java.awt.Font("Leelawadee UI", 0, 10)); // NOI18N
        jLabel11.setText("Time loss Reasons ");
        add(jLabel11);
        jLabel11.setBounds(800, 0, 90, 30);

        jLabel12.setFont(new java.awt.Font("Leelawadee UI", 0, 10)); // NOI18N
        jLabel12.setText("Actual Quantity");
        add(jLabel12);
        jLabel12.setBounds(490, 0, 80, 30);

        jLabel13.setFont(new java.awt.Font("Leelawadee UI", 0, 10)); // NOI18N
        jLabel13.setText("Rejections");
        add(jLabel13);
        jLabel13.setBounds(600, 0, 80, 30);

        jLabel14.setFont(new java.awt.Font("Leelawadee UI", 0, 10)); // NOI18N
        jLabel14.setText("Rejection Reasons");
        add(jLabel14);
        jLabel14.setBounds(690, 0, 80, 30);

        jLabel3.setFont(new java.awt.Font("Leelawadee UI", 0, 10)); // NOI18N
        jLabel3.setText("Target QTY");
        add(jLabel3);
        jLabel3.setBounds(230, 0, 70, 30);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
