/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trixware.erp.prodezydesktop.examples;

/**
 *
 * @author Rajesh
 */
public class Users extends javax.swing.JPanel {

    /**
     * Creates new form Users
     */
    public Users() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        jCheckBox1.setText("jCheckBox1");

        setBorder(javax.swing.BorderFactory.createTitledBorder("Users"));
        setLayout(null);

        jLabel1.setText("Username ");
        add(jLabel1);
        jLabel1.setBounds(30, 40, 51, 20);
        add(jTextField1);
        jTextField1.setBounds(110, 40, 160, 20);

        jLabel2.setText("Password");
        add(jLabel2);
        jLabel2.setBounds(30, 70, 46, 20);

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        add(jTextField2);
        jTextField2.setBounds(110, 70, 160, 20);

        jLabel3.setText("Re-password ");
        add(jLabel3);
        jLabel3.setBounds(30, 100, 66, 20);
        add(jTextField3);
        jTextField3.setBounds(110, 100, 160, 20);

        jLabel4.setText("Name");
        add(jLabel4);
        jLabel4.setBounds(30, 200, 51, 20);
        add(jTextField4);
        jTextField4.setBounds(110, 200, 160, 20);

        jLabel5.setText("Address");
        add(jLabel5);
        jLabel5.setBounds(30, 230, 39, 20);
        add(jTextField5);
        jTextField5.setBounds(110, 230, 160, 20);

        jLabel6.setText("Phone");
        add(jLabel6);
        jLabel6.setBounds(30, 260, 30, 20);
        add(jTextField6);
        jTextField6.setBounds(110, 260, 160, 20);

        jLabel7.setText("Role");
        add(jLabel7);
        jLabel7.setBounds(30, 360, 50, 20);
        add(jTextField7);
        jTextField7.setBounds(110, 290, 160, 20);

        jLabel8.setText("Designation");
        add(jLabel8);
        jLabel8.setBounds(30, 290, 80, 20);

        jLabel9.setText("<html>Nature of <br>Employment</html>");
        add(jLabel9);
        jLabel9.setBounds(30, 320, 70, 30);

        add(jComboBox1);
        jComboBox1.setBounds(110, 320, 160, 20);

        jLabel10.setText("User Details");
        add(jLabel10);
        jLabel10.setBounds(30, 150, 70, 20);

        add(jComboBox2);
        jComboBox2.setBounds(110, 150, 160, 20);

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("--- OR ---");
        add(jLabel11);
        jLabel11.setBounds(120, 180, 140, 14);

        add(jComboBox3);
        jComboBox3.setBounds(110, 360, 160, 20);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1);
        jScrollPane1.setBounds(330, 30, 210, 350);

        jButton1.setText("Cancel");
        add(jButton1);
        jButton1.setBounds(140, 410, 65, 23);

        jButton2.setText("Add new user");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2);
        jButton2.setBounds(220, 410, 100, 23);

        jButton3.setText("Edit");
        add(jButton3);
        jButton3.setBounds(330, 410, 51, 23);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        
        
        
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    // End of variables declaration//GEN-END:variables
}
