/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trixware.erp.prodezydesktop.masters;

import java.awt.Desktop;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.nio.channels.FileChannel;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Vector;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.apache.poi.hssf.usermodel.HSSFCellStyle;
import org.apache.poi.hssf.usermodel.HSSFWorkbook;
import org.apache.poi.hssf.util.HSSFColor;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.CellStyle;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;
import trixware.erp.prodezydesktop.Utilities.DB_Operations;
import trixware.erp.prodezydesktop.Utilities.MyCustomFilter;
import trixware.erp.prodezydesktop.examples.HomeScreen3;

/**
 *
 * @author Rajesh
 */
public class Calibration extends javax.swing.JPanel {

    /**
     * Creates new form Calibration
     */
    public Calibration() {
        initComponents();
        int a = 5;
    }

    public void loadContent() {
        try {
            ResultSet result = DB_Operations.getMasters("calibration");
            // jTable1.setModel(DbUtils.resultSetToTableModel(result)); 

            if (result != null) {
                jTable1.setModel(buildTableModel(result));
            }

            jTable1.getColumnModel().getColumn(0).setMinWidth(0);
            jTable1.getColumnModel().getColumn(0).setMaxWidth(0);

          //  result = DB_Operations.getMasters("supplier");
         //   if (result != null) {
         //       while (result.next()) {
        //            jComboBox2.addItem( result.getString("SUPP_NAME"));
        //        }
         //   }

        } catch (SQLException e) {

        }
    }

    public static DefaultTableModel buildTableModel(ResultSet rs)
            throws SQLException {

        ResultSetMetaData metaData = rs.getMetaData();

        // names of columns
        Vector<String> columnNames = new Vector<String>();
        int columnCount = metaData.getColumnCount();
        for (int column = 1; column <= 4; column++) {
            columnNames.add(metaData.getColumnName(column));
        }

        // data of the table
        Vector<Vector<Object>> data = new Vector<Vector<Object>>();
        while (rs.next()) {
            Vector<Object> vector = new Vector<Object>();
            for (int columnIndex = 1; columnIndex <= 4; columnIndex++) {
                vector.add(rs.getObject(columnIndex));
            }
            data.add(vector);
        }

        return new DefaultTableModel(data, columnNames);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBox8 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jComboBox9 = new javax.swing.JComboBox<>();
        dateChooserCombo1 = new datechooser.beans.DateChooserCombo();
        dateChooserCombo2 = new datechooser.beans.DateChooserCombo();
        jLabel7 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Calibration"));
        setLayout(null);

        jTable1.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        add(jScrollPane2);
        jScrollPane2.setBounds(10, 380, 1300, 210);

        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane3.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
        jLabel1.setText("Equippment");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(30, 10, 100, 30);

        jComboBox1.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Equippment 1", "Equippment 2", "Equippment 3" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(160, 10, 210, 30);

        jLabel2.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
        jLabel2.setText("Calibration Date");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 50, 100, 30);

        jLabel3.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
        jLabel3.setText("Next Due Date");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 90, 100, 30);

        jLabel4.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
        jLabel4.setText("Calibration Agency");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(30, 130, 120, 30);

        jComboBox8.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
        jComboBox8.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Agency 1", "Agency 2", "Agency 3" }));
        jComboBox8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox8ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox8);
        jComboBox8.setBounds(160, 130, 210, 32);

        jLabel5.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
        jLabel5.setText("Calibration Frequency");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(30, 170, 130, 30);

        jComboBox9.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
        jComboBox9.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Not  needed", "As per need", "Daily", "Weekly", "Twice a week", "Monthly", "Bi-monthly", "Quarterly", "Yearly", "Bienniel", " ", " " }));
        jComboBox9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox9ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox9);
        jComboBox9.setBounds(160, 170, 210, 30);

        dateChooserCombo1.setCalendarPreferredSize(new java.awt.Dimension(400, 320));
        dateChooserCombo1.setFieldFont(new java.awt.Font("Leelawadee UI", java.awt.Font.PLAIN, 12));
        jPanel1.add(dateChooserCombo1);
        dateChooserCombo1.setBounds(160, 90, 210, 30);

        dateChooserCombo2.setCalendarPreferredSize(new java.awt.Dimension(400, 320));
        dateChooserCombo2.setFieldFont(new java.awt.Font("Leelawadee UI", java.awt.Font.PLAIN, 12));
        jPanel1.add(dateChooserCombo2);
        dateChooserCombo2.setBounds(160, 50, 210, 30);

        jLabel7.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
        jLabel7.setText("Certificate Copy");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(30, 200, 100, 30);

        jTextField2.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
        jTextField2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField2MouseClicked(evt);
            }
        });
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField2);
        jTextField2.setBounds(160, 210, 210, 30);

        jComboBox2.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox2);
        jComboBox2.setBounds(620, 90, 210, 30);

        jLabel10.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setText("<html>Equippment<br>Supplier</html>");
        jLabel10.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jPanel1.add(jLabel10);
        jLabel10.setBounds(480, 90, 100, 32);

        jLabel11.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel11.setText("<html>Equippment<br>Make</html>");
        jLabel11.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jPanel1.add(jLabel11);
        jLabel11.setBounds(480, 50, 100, 32);

        jTextField4.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
        jPanel1.add(jTextField4);
        jTextField4.setBounds(620, 50, 210, 30);

        jLabel6.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
        jLabel6.setText("<html>NABL<br> Certificate No");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(480, 0, 100, 50);

        jTextField1.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
        jPanel1.add(jTextField1);
        jTextField1.setBounds(620, 10, 210, 30);

        jLabel8.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
        jLabel8.setText("<html>Agency Contact<br>Details</html>");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(890, 30, 100, 30);

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(1030, 20, 220, 100);

        jButton1.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
        jButton1.setText("Select Copy");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(280, 240, 92, 30);
        jButton1.getAccessibleContext().setAccessibleName("");

        jScrollPane3.setViewportView(jPanel1);

        add(jScrollPane3);
        jScrollPane3.setBounds(10, 20, 1300, 290);

        jButton2.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
        jButton2.setText("Add to Master");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2);
        jButton2.setBounds(890, 320, 105, 32);

        jButton6.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
        jButton6.setText("Edit");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        add(jButton6);
        jButton6.setBounds(1000, 320, 60, 32);

        jButton7.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
        jButton7.setText("Reset");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        add(jButton7);
        jButton7.setBounds(1060, 320, 58, 32);

        jButton4.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
        jButton4.setText("Export to Excel");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        add(jButton4);
        jButton4.setBounds(1120, 320, 106, 32);

        jButton3.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
        jButton3.setText("Cancel");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3);
        jButton3.setBounds(1230, 320, 66, 32);
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox8ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        String EQUIPPMENT_NAME, CALIBRATION_DATE, NEXT_DUE_DATE, CALIBRATION_AGENCY, CALIBRATION_FREQUENCY, NABL_CERTIFICATE_NO, CERTIFICATE_COPY, AGENCY_CONTACT_DETAILS, INSTR_LIST, SUPPLIER, EQP_MAKE, CREATED_ON, EDITED_ON, EDITED_BY;

        EQUIPPMENT_NAME = jComboBox1.getSelectedItem().toString();
        //CALIBRATION_DATE = String.valueOf(jComboBox2.getSelectedItem().toString() + ", " + jComboBox3.getSelectedItem().toString() + ", " + jComboBox4.getSelectedItem().toString());
        //NEXT_DUE_DATE = String.valueOf(jComboBox5.getSelectedItem().toString() + ", " + jComboBox6.getSelectedItem().toString() + ", " + jComboBox7.getSelectedItem().toString());

        CALIBRATION_DATE = String.valueOf(dateChooserCombo2.getText());
        NEXT_DUE_DATE = String.valueOf(dateChooserCombo1.getText());

        CALIBRATION_AGENCY = jComboBox8.getSelectedItem().toString();
        CALIBRATION_FREQUENCY = jComboBox9.getSelectedItem().toString();
        NABL_CERTIFICATE_NO = jTextField1.getText();
        CERTIFICATE_COPY = jTextField2.getText();
        AGENCY_CONTACT_DETAILS = jTextArea1.getText();

        INSTR_LIST = "";
      //  int i = 0;
     //   while (i < instrumentList.size()) {
     //       if (i == instrumentList.size() - 1) {
     //           INSTR_LIST = INSTR_LIST + instrumentList.get(i);
      //      } else {
     //          INSTR_LIST = INSTR_LIST + instrumentList.get(i) + ",";
      //      }
     //       i++;
     //   }

        SUPPLIER = jComboBox2.getSelectedItem().toString();

        EQP_MAKE = jTextField4.getText();

        CREATED_ON = "CREATED_ON";
        EDITED_ON = "EDITED_BY";
        EDITED_BY = "EDITED_ON";

        String result = DB_Operations.insertIntoCalibrationMaster(EQUIPPMENT_NAME, CALIBRATION_DATE, NEXT_DUE_DATE, CALIBRATION_AGENCY, CALIBRATION_FREQUENCY, NABL_CERTIFICATE_NO, CERTIFICATE_COPY, AGENCY_CONTACT_DETAILS, INSTR_LIST, SUPPLIER, EQP_MAKE, CREATED_ON, EDITED_ON, EDITED_BY);

        JOptionPane.showMessageDialog(null, "" + result);

        loadContent();

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        Workbook wb = new HSSFWorkbook();

        ArrayList<String> column_names = new ArrayList<String>();
        ArrayList<String[]> values = new ArrayList<String[]>();
        int columnCount = 0;
        File file = null;
        try {
            ResultSet result = DB_Operations.getMasters("calibration");
            if (result != null) {
                ResultSetMetaData metaData = result.getMetaData();
                // names of columns
                columnCount = metaData.getColumnCount();
                for (int column = 1; column <= columnCount - 3; column++) {
                    column_names.add(metaData.getColumnName(column));
                }
            }
            // data of the table
            Vector<Vector<Object>> data = new Vector<Vector<Object>>();
            while (result.next()) {
                String[] val = new String[columnCount];
                for (int columnIndex = 1; columnIndex <= columnCount; columnIndex++) {
                    if (columnIndex < columnCount - 2) {
                        val[columnIndex - 2] = String.valueOf(result.getObject(columnIndex));
                    }
                }
                values.add(val);
            }
        } catch (SQLException e) {

        }

        // Cell style for header row
        CellStyle cs = wb.createCellStyle();
        //cs.setFillForegroundColor(HSSFColor.LIME.index);
        //cs.setFillPattern(HSSFCellStyle.SOLID_FOREGROUND);

        CellStyle cs2 = wb.createCellStyle();
        cs2.setFillForegroundColor(HSSFColor.ROSE.index);
        cs2.setFillPattern(HSSFCellStyle.SOLID_FOREGROUND);

        // New Sheet
        Sheet sheet1 = null;
        sheet1 = wb.createSheet("Calibration Master");
        sheet1.setColumnWidth(0, (15 * 500));

        Cell c = null;
        Cell c3 = null;

        Row row = sheet1.createRow(1);
        //  c = row.createCell(0);
        // c.setCellValue("");
        // c.setCellStyle(cs);

        int i = 1;
        //add column names to the firt row of excel
        row = sheet1.createRow(i++);
        for (int a = 0; a < column_names.size(); a++) {
            c = row.createCell(a);
            // c.setCellValue(cursor.getString(a));
            c.setCellValue(column_names.get(a));
            c.setCellStyle(cs);
        }

        for (int j = 0; j < values.size(); j++) {
            String[] rowValues = values.get(j);
            Row row4 = sheet1.createRow(i++);
            for (int k = 0; k < rowValues.length; k++) {
                {

                    c = row4.createCell(k);
                    c.setCellValue(rowValues[k]);
                    c.setCellStyle(cs);
                }
            }
            Calendar c2 = Calendar.getInstance();
            SimpleDateFormat sdf2 = new SimpleDateFormat("ddMMMyyyy_HH_mm_a");
            String strDate2 = sdf2.format(c2.getTime());
            file = new File("Calibration MasterFile " + strDate2 + ".xls");

            FileOutputStream os = null;

            try {
                os = new FileOutputStream(file);
                wb.write(os);
                wb.close();
                os.close();

            } catch (IOException e) {
                JOptionPane.showMessageDialog(null, "Error " + e.getMessage());
            } finally {

            }

        }
        JOptionPane.showMessageDialog(null, "New File generated at " + file.getAbsolutePath());
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        System.out.println("mouse Clicked");

        ArrayList<String> values = new ArrayList<String>();
        ArrayList<byte[]> files = new ArrayList<byte[]>();
        int columnCount = 0;
        // get the model from the jtable
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

        // get the selected row index
        int selectedRowIndex = jTable1.getSelectedRow();
        
        selectedCalibrationID = Integer.parseInt(model.getValueAt(selectedRowIndex, 0).toString());
        // Integer.parseInt(model.getValueAt(selectedRowIndex, 0).toString() )
        //         JOptionPane.showMessageDialog(null, "" + model.getValueAt(selectedRowIndex, 0).toString() );
        try {
            ResultSet result = DB_Operations.getSingleMasters("calibration", Integer.parseInt(model.getValueAt(selectedRowIndex, 0).toString()));

            // System.out.println("selected record id " + Integer.parseInt(model.getValueAt(selectedRowIndex, 0).toString()));
            if (result != null) {
                ResultSetMetaData metaData = result.getMetaData();

                columnCount = metaData.getColumnCount();

                while (result.next()) {

                    for (int columnIndex = 1; columnIndex <= columnCount; columnIndex++) {
                        if (columnIndex < columnCount - 2) {

                            values.add(String.valueOf(result.getObject(columnIndex)));
                            System.out.println(" " + String.valueOf(result.getObject(columnIndex)));

                        }
                    }
                }
            }
        } catch (SQLException e) {

            System.out.println("Error " + e.getMessage());
        }

        /* equppment name */ jComboBox1.setSelectedItem(values.get(1));
        /* calibration date */ dateChooserCombo2.setText(values.get(2));
        /* next due date */ dateChooserCombo1.setText(values.get(3));
        /*  calibration agency  */ jComboBox8.setSelectedItem(values.get(4));
        /*calibration frequency */ jComboBox9.setSelectedItem(values.get(5));
        /*  nabl certificate no  */ jTextField2.setText(values.get(7));
        /*  certificate copy */ jTextField1.setText(values.get(6));
        /* agcny contact details */ jTextArea1.setText(values.get(8));

      //  String[] instrList = values.get(9).split(",");
      //  instrumentList.removeAllElements();
     //   for (int i = 0; i < instrList.length; i++) {
     //       System.out.println(instrList[i]);
     //       instrumentList.addElement(instrList[i]);
     //   }
        //jList1.setModel(instrumentList);

        jTextField4.setText(values.get(11));
        jComboBox2.setSelectedItem(values.get(10));

        jButton2.setEnabled(false);
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    DefaultListModel<String> instrumentList = new DefaultListModel<>();

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        HomeScreen3.home.removeAll();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        resetFields();
        jButton2.setEnabled(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        
        String EQUIPPMENT_NAME, CALIBRATION_DATE, NEXT_DUE_DATE, CALIBRATION_AGENCY, CALIBRATION_FREQUENCY, NABL_CERTIFICATE_NO, CERTIFICATE_COPY, AGENCY_CONTACT_DETAILS, INSTR_LIST, SUPPLIER, EQP_MAKE,  EDITED_ON, EDITED_BY;
        int ID ;

        EQUIPPMENT_NAME = jComboBox1.getSelectedItem().toString();
        CALIBRATION_DATE = String.valueOf(dateChooserCombo2.getText());
        NEXT_DUE_DATE = String.valueOf(dateChooserCombo1.getText());
        CALIBRATION_AGENCY = jComboBox8.getSelectedItem().toString();
        CALIBRATION_FREQUENCY = jComboBox9.getSelectedItem().toString();
        NABL_CERTIFICATE_NO = jTextField1.getText();
        CERTIFICATE_COPY = jTextField2.getText();
        AGENCY_CONTACT_DETAILS = jTextArea1.getText();

        INSTR_LIST = "";
        int i = 0;
        while (i < instrumentList.size()) {
            if (i == instrumentList.size() - 1) {
                INSTR_LIST = INSTR_LIST + instrumentList.get(i);
            } else {
                INSTR_LIST = INSTR_LIST + instrumentList.get(i) + ",";
            }
            i++;
        }

        SUPPLIER = jComboBox2.getSelectedItem().toString();

        EQP_MAKE = jTextField4.getText();

        EDITED_ON = "EDITED_BY";
        EDITED_BY = "EDITED_ON";

        ID = selectedCalibrationID ;
        
        String result = DB_Operations.updateCalibrationMaster(EQUIPPMENT_NAME, CALIBRATION_DATE, NEXT_DUE_DATE, CALIBRATION_AGENCY, CALIBRATION_FREQUENCY, NABL_CERTIFICATE_NO, CERTIFICATE_COPY, AGENCY_CONTACT_DETAILS, INSTR_LIST, SUPPLIER, EQP_MAKE, EDITED_ON, EDITED_BY, ID);

        JOptionPane.showMessageDialog(null, "" + result);

        loadContent();
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jComboBox9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox9ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jTextField2.setText( createFileNameResource( "NABLCertificateCopy") );
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField2MouseClicked
        // TODO add your handling code here:
        openFile(jTextField2.getText());
    }//GEN-LAST:event_jTextField2MouseClicked

    public void resetFields() {

        jTextField1.setText("");
        jTextField2.setText("");
        jTextArea1.setText("");
        jTextField4.setText("");
   //     DefaultListModel<String> model =  (DefaultListModel) jList1.getModel();
   //     model.removeAllElements();
    //    jList1.setModel(model);
    }

public String createFileNameResource(String columnDocumentName){
        
        Calendar c2 = Calendar.getInstance();
            SimpleDateFormat sdf2 = new SimpleDateFormat("ddMMMyyyy_HH_mm_a");
            String strDate2 = sdf2.format(c2.getTime());
                   
            FileChannel inputChannel = null;
            FileChannel outputChannel = null;
            
             JFileChooser fileChooser = new JFileChooser();
             fileChooser.setFileFilter(new MyCustomFilter());
             fileChooser.setCurrentDirectory(new File(System.getProperty("user.home")));
             int result = fileChooser.showOpenDialog(this);
             if (result == JFileChooser.APPROVE_OPTION) {
             File selectedFile = fileChooser.getSelectedFile();
            
            File dir = new File("UploadedFiles");
            dir.mkdir();
            
            partDrawingFile_name = columnDocumentName+"_("+selectedFile.getName()+") _saved_on"+ strDate2 + selectedFile.getName().substring(selectedFile.getName().lastIndexOf( '.' ));
            
            try {
                inputChannel = new FileInputStream( selectedFile ).getChannel();
                outputChannel = new FileOutputStream(new File(dir, partDrawingFile_name)).getChannel();
                outputChannel.transferFrom(inputChannel, 0, inputChannel.size());

                inputChannel.close();
                outputChannel.close();
        
            }catch(FileNotFoundException e1){

            }catch(IOException e2){

            }
        }             
             return partDrawingFile_name ;
    }
    
    
    public void openFile(String filename){
        
         if(! filename .equals("") ){
            try {
                String fileName = filename;
                
                File dir = new File( "uploadedFiles" );
                
                File file = new File( dir, fileName );
                
                Desktop desktop = Desktop.getDesktop();
                if(file.exists()) 
                    desktop.open(file);
            } catch (IOException ex) {
            //    Logger.getLogger(FinishedGoodMaster.class.getName()).log(Level.SEVERE, null, ex);
            }                
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private datechooser.beans.DateChooserCombo dateChooserCombo1;
    private datechooser.beans.DateChooserCombo dateChooserCombo2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox8;
    private javax.swing.JComboBox<String> jComboBox9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables

    int selectedCalibrationID = 0;
    String partDrawingFile_name = "";
}
