/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trixware.erp.prodezydesktop.masters;

/**
 *
 * @author Rajesh
 */
public class EquippmentMaster extends javax.swing.JPanel {

    /**
     * Creates new form EquippmentMaster
     */
    public EquippmentMaster() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setOpaque(false);
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
        jLabel1.setText("Equippment Name");
        add(jLabel1);
        jLabel1.setBounds(30, 30, 100, 20);

        jLabel2.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
        jLabel2.setText("Equippment ID");
        add(jLabel2);
        jLabel2.setBounds(30, 80, 100, 20);

        jLabel3.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
        jLabel3.setText("Make");
        add(jLabel3);
        jLabel3.setBounds(230, 30, 100, 20);

        jLabel4.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
        jLabel4.setText("Type");
        add(jLabel4);
        jLabel4.setBounds(230, 80, 100, 20);

        jLabel5.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
        jLabel5.setText("Size / Capacity");
        add(jLabel5);
        jLabel5.setBounds(430, 30, 100, 20);
        add(jTextField1);
        jTextField1.setBounds(30, 50, 160, 30);
        add(jTextField2);
        jTextField2.setBounds(30, 100, 160, 30);
        add(jTextField3);
        jTextField3.setBounds(230, 50, 160, 30);
        add(jTextField4);
        jTextField4.setBounds(230, 100, 160, 30);
        add(jTextField5);
        jTextField5.setBounds(430, 50, 160, 30);

        jLabel6.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
        jLabel6.setText("Ownership");
        add(jLabel6);
        jLabel6.setBounds(430, 80, 100, 20);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(jComboBox1);
        jComboBox1.setBounds(430, 100, 160, 30);
        add(jScrollPane1);
        jScrollPane1.setBounds(20, 180, 890, 210);

        jButton1.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
        jButton1.setText("Add to master");
        add(jButton1);
        jButton1.setBounds(640, 40, 120, 32);

        jButton2.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
        jButton2.setText("Edit");
        add(jButton2);
        jButton2.setBounds(640, 80, 120, 32);

        jToggleButton1.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
        jToggleButton1.setText("Reset");
        add(jToggleButton1);
        jToggleButton1.setBounds(640, 120, 120, 32);

        jButton3.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
        jButton3.setText("Cancel");
        add(jButton3);
        jButton3.setBounds(770, 40, 120, 32);

        jButton4.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
        jButton4.setText("Export to Excel");
        add(jButton4);
        jButton4.setBounds(770, 80, 120, 32);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
