/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trixware.erp.prodezydesktop.masters;

import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import trixware.erp.prodezydesktop.Model.StaticValues;
import trixware.erp.prodezydesktop.examples.HomeScreen;

/**
 *
 * @author Rajesh
 */
public class Process_Master_Form3 extends javax.swing.JPanel {

    Connection con;
    PreparedStatement pst;
    ResultSet rs;
    String resource = "" , resourceType = "" ;
    
    /**
     * Creates new form Process_Master_Form
     */
    public Process_Master_Form3 () {
        initComponents ();
                
        resourceType = "Masters" ;
	resource = "Process_Master_Form3" ;

	try{
      		StaticValues.checkUserRolePermission(resourceType, resourceType);
	   }catch(Exception e){
      		StaticValues.writer.writeExcel (resource , resource , e.getClass ().toString () , Thread.currentThread ().getStackTrace ()[ 1 ].getLineNumber () + "" , e.getMessage () , StaticValues.sdf2.format ( Calendar.getInstance ().getTime () ) );
   	   }
        
        try {

            File f = new File("srirubber-v3.db");
            if (f.exists()) {
            
               con = DriverManager.getConnection("jdbc:sqlite:srirubber-v3.db");
                
                pst = con.prepareStatement ( ""  ) ;
                pst.execute ();
               
                loadContent ();
            }
        } catch (SQLException ex) {
           System.out.println ( ex.getMessage () );
        }finally{
            try{
                pst.close();
            }catch(Exception e){
                System.out.println ( e.getMessage () );
            }
        }

    }

    public void loadContent(){
        
        try{
                String getAllProcesses = "SELECT * FROM PROCESS_MASTER";
                pst = con.prepareStatement ( getAllProcesses  ) ;
                rs = pst.executeQuery ();
                
                jTable1.setModel( buildTableModel ( rs ) );
                jTable1.getColumnModel().getColumn(0).setMinWidth(0);
                jTable1.getColumnModel().getColumn(0).setMaxWidth(0);

        } catch (SQLException ex) {
            // Logger.getLogger(DB_Operations.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "" + ex.getMessage());
            System.out.println("DB not Connected");
        }finally{
            try{
                rs.close();
                pst.close();
            }catch(Exception e){
                System.out.println ( e.getMessage () );
            }
        }
    }

    public static DefaultTableModel buildTableModel(ResultSet rs)
            throws SQLException {

        ResultSetMetaData metaData = rs.getMetaData();

        // names of columns
        Vector<String> columnNames = new Vector<String>();
        int columnCount = metaData.getColumnCount();
        for (int column = 1; column <= 3; column++) {
            columnNames.add(metaData.getColumnName(column));
        }

        // data of the table
        Vector<Vector<Object>> data = new Vector<Vector<Object>>();
        while (rs.next()) {
            Vector<Object> vector = new Vector<Object>();
            for (int columnIndex = 1; columnIndex <= 3 ; columnIndex++) {
                vector.add(rs.getObject(columnIndex));
            }
            data.add(vector);
        }

        return new DefaultTableModel(data, columnNames);

    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings( "unchecked" )
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel26 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jLabel27 = new javax.swing.JLabel();

        setOpaque(false);
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
        jLabel1.setText("Process Name");
        add(jLabel1);
        jLabel1.setBounds(70, 66, 75, 30);

        jButton1.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
        jButton1.setText("Add to master");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(650, 70, 120, 32);

        jTextField1.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
        add(jTextField1);
        jTextField1.setBounds(190, 70, 330, 30);

        jButton2.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
        jButton2.setText("Update");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2);
        jButton2.setBounds(650, 110, 120, 32);

        jButton3.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
        jButton3.setText("Reset Form");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        add(jButton3);
        jButton3.setBounds(650, 150, 120, 32);

        jButton4.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
        jButton4.setText("Cancel");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        add(jButton4);
        jButton4.setBounds(650, 230, 120, 32);

        jButton5.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
        jButton5.setText("Export to Excel");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        add(jButton5);
        jButton5.setBounds(650, 190, 120, 32);

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane3.setViewportView(jTextArea1);

        add(jScrollPane3);
        jScrollPane3.setBounds(190, 150, 330, 83);

        jLabel2.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
        jLabel2.setText("Process Details");
        add(jLabel2);
        jLabel2.setBounds(70, 150, 78, 16);

        jTable1.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Process Title"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        add(jScrollPane2);
        jScrollPane2.setBounds(70, 240, 450, 180);

        jLabel26.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 0, 51));
        jLabel26.setText("*");
        add(jLabel26);
        jLabel26.setBounds(60, 120, 30, 10);

        jLabel3.setText("Type");
        add(jLabel3);
        jLabel3.setBounds(70, 100, 27, 40);

        jCheckBox1.setText("Batch Wise");
        add(jCheckBox1);
        jCheckBox1.setBounds(190, 110, 93, 24);

        jCheckBox2.setText("Item Wise");
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });
        add(jCheckBox2);
        jCheckBox2.setBounds(300, 110, 85, 24);

        jLabel27.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 0, 51));
        jLabel27.setText("*");
        add(jLabel27);
        jLabel27.setBounds(60, 80, 30, 10);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:
        HomeScreen.home.removeForms ();
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        
        
        String process_name = jTextField1.getText ().toString () ;
        String process_details = jTextArea1.getText ().toString () ;
        
        if( !process_name.equalsIgnoreCase ( "" )){
            try{
                pst = con.prepareStatement (" insertQuery  ") ;
                pst.setString ( 1,  process_name);
                pst.setString ( 2, process_details);

                pst.executeUpdate ();

                loadContent ();

                resetForm ();

            }catch(  SQLException e ){
                   System.out.println ( e.getMessage () );
            }finally{
                try{

                    pst.close();
                }catch(Exception e){
                    System.out.println ( e.getMessage () );
                }
            }
        }else{
            
            JOptionPane.showMessageDialog(null, " Please insert appropriate process name ! ");
            
        }
        
        jTextField1.requestFocus ();
    }//GEN-LAST:event_jButton1MouseClicked

    public void resetForm(){
        
        jTextArea1.setText ( "" );
        jTextField1.setText ( "" );
        jButton1.setEnabled(true);
        jButton2.setEnabled(false);
        
    }
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
          // TODO add your handling code here:
        jButton1.setEnabled(false);
        jButton2.setEnabled(true);
                
        ArrayList<String> values = new ArrayList<String>();
        // get the model from the jtable
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        int columnCount = 0;
        // get the selected row index
        int selectedRowIndex = jTable1.getSelectedRow();
        // Integer.parseInt(model.getValueAt(selectedRowIndex, 0).toString() )
        // JOptionPane.showMessageDialog(null, "" + model.getValueAt(selectedRowIndex, 0).toString() );
        try {
            
            selectedProcessId = Integer.parseInt(model.getValueAt(selectedRowIndex, 0).toString());
            
          String getAllProcesses = "SELECT * FROM PROCESS_MASTER WHERE PROCESS_ID = "+selectedProcessId;
                
                pst = con.prepareStatement ( getAllProcesses  ) ;
                rs = pst.executeQuery ();
            
            if (rs != null) {
                ResultSetMetaData metaData = rs.getMetaData();

                columnCount = metaData.getColumnCount();

                while (rs.next()) {

                    for (int columnIndex = 1; columnIndex <= columnCount; columnIndex++) {
                        
                           values.add(String.valueOf(rs.getObject(columnIndex)));
                    }
                }
            }
        } catch (SQLException e) {

            System.out.println("Error " + e.getMessage());
        }finally{
            try{
                rs.close();
                pst.close();
            }catch(Exception e){
                System.out.println ( e.getMessage () );
            }
        }

          jTextArea1.setText(values.get(2));
          jTextField1.setText(values.get(1));
       
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        resetForm ();
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        String updateQury = "UPDATE PROCESS_MASTER SET   PROCESS_NAME = ?, PROCESS_DETAILS = ? WHERE PROCESS_ID = ?  ";
        
        String process_name = jTextField1.getText ().toString () ;
        String process_details = jTextArea1.getText ().toString () ;
        
        try{
            pst = con.prepareStatement ( updateQury  ) ;
            pst.setString ( 1,  process_name);
            pst.setString ( 2, process_details);
            pst.setInt ( 3, selectedProcessId);
            
            pst.executeUpdate ();
            
            loadContent ();
            
            resetForm ();
            
        }catch(  SQLException e ){
               System.out.println ( e.getMessage () );
        }finally{
            try{
                
                pst.close();
            }catch(Exception e){
                 System.out.println ( e.getMessage () );
            }
        }
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    public javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

    int selectedProcessId = 0;
}
