/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trixware.erp.prodezydesktop.masters;

import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.util.ArrayList;
import java.util.Calendar;
import javax.swing.JTextField;
import trixware.erp.prodezydesktop.Model.BOMModel;
import trixware.erp.prodezydesktop.Model.StaticValues;
import trixware.erp.prodezydesktop.Model.UOMDR;

/**
 *
 * @author Rajesh
 */
public class RMQtyPanel extends javax.swing.JPanel {

    BOMModel bomModel ;
    
    int rmid,  rmuom;
    String rmname ;
    double rmqty ;
    /**
     * Creates new form RMQtys
     */
    public RMQtyPanel () {
        initComponents ();
        bomModel = new BOMModel ();
   
        jTextField1.addKeyListener ( k );
        jTextField1.addFocusListener ( f2 );
        jComboBox1.setVisible ( false );
    }
    
   
    public void setFgid ( int fgid ) {
        
        bomModel.setFgid ( fgid ) ;        
    }

    public int getRmid () {       
       
        return this.rmid ;
    }

    public void setRmid ( int rmid ) {    
        this.rmid = rmid ;
         bomModel.setRmid ( rmid );
        jLabel1.setText (rmid+"" );
        
    }

    public double getQty () {
        rmqty = Double.parseDouble( this.jTextField1.getText ().trim ( ) )  ;
       
        return rmqty ;
    }

    public void SetQty (  double val) {       
        rmqty = val ;
        bomModel.setQty ( val );
        jTextField1.setText(""+val ) ;
    }
    
    public int getUomList () {
        return  jComboBox1.getSelectedIndex () ;
    }

    public void setUomList ( ArrayList<UOMDR> uomList) {
         
        bomModel.setUomList ( uomList );
        jComboBox1.removeAll ();
        for( int i=0; i<uomList.size (); i++ ){
            jComboBox1.addItem ( uomList.get ( i ).UOM_NAME );
            
        }
        jComboBox1.revalidate ();
     }

    public String getRMName () {
        return this.rmname;
    }

    public void setRMName ( String _rmname ) {      
        bomModel.setRMName (_rmname);
        rmname = _rmname ;
        jLabel2.setText ( _rmname );
    }

    public int getRmuom () {
        return rmuom;
    }

    public void setRmuom ( int rmuom ) {
        this.rmuom = rmuom;
        jLabel3.setText(  StaticValues.getUOMName ( rmuom ) ) ;
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings( "unchecked" )
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(400, 60));
        setLayout(null);
        add(jLabel1);
        jLabel1.setBounds(0, 0, 0, 0);
        add(jLabel2);
        jLabel2.setBounds(5, 5, 150, 30);

        jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField1FocusGained(evt);
            }
        });
        add(jTextField1);
        jTextField1.setBounds(190, 4, 54, 30);

        add(jComboBox1);
        jComboBox1.setBounds(251, 6, 50, 26);

        jLabel3.setText("jLabel3");
        add(jLabel3);
        jLabel3.setBounds(310, 0, 50, 30);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1FocusGained

    KeyListener k = new KeyListener () {
        @Override
        public void keyTyped ( KeyEvent e ) {
           char enter = e.getKeyChar();
            String dot = Character.toString ( enter );
            if (  ! ( Character.isDigit ( enter ) )  && ! dot.equals ( ".")) {
                    e.consume ();
            }
        }

        @Override
        public void keyPressed ( KeyEvent e ) {
        }

        @Override
        public void keyReleased ( KeyEvent e ) {
        }
    };
    
    FocusListener f2 = new FocusListener () {
        @Override
        public void focusGained ( FocusEvent e ) {
//            throw new UnsupportedOperationException ( "Not supported yet." ); //To change body of generated methods, choose Tools | Templates.
            JTextField jcb = ( JTextField ) e.getSource ();    
            jcb.setText("");
        }

        @Override
        public void focusLost ( FocusEvent e ) {
        //    throw new UnsupportedOperationException ( "Not supported yet." ); //To Search Google or type URL
//change body of generated methods, choose Tools | Templates.
            JTextField jcb = ( JTextField ) e.getSource ();    
            String x = jcb.getText().trim ();
            
            if(x.equalsIgnoreCase ( "")){
                x = "0";
            }
            
            try{    
                int num  = Integer.parseInt( String.valueOf( jcb.getText().toString() ) );
                    if( num<0  ){
                     jcb.setText(x);
                     
                    //evt.consume ();
                }
            }catch(NumberFormatException ex1){
                    jcb.setText(x);
                    StaticValues.writer.writeExcel (RMQtyPanel.class.getSimpleName () , RMQtyPanel.class.getSimpleName () , ex1.getClass ().toString () , Thread.currentThread ().getStackTrace ()[ 1 ].getLineNumber () + "" , ex1.getMessage () , StaticValues.sdf2.format ( Calendar.getInstance ().getTime () ) );            
            }
        }
    };

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    public static javax.swing.JLabel jLabel1;
    public static javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
