/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trixware.erp.prodezydesktop.quotation;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import org.json.JSONArray;
import org.json.JSONObject;
import trixware.erp.prodezydesktop.Model.StaticValues;
import trixware.erp.prodezydesktop.web_services.WebAPITester;

/**
 *
 * @author Akshay
 */
public class EnquiryDetails extends javax.swing.JPanel {

    /**
     * Creates new form EnquiryDetails
     */
    private ArrayList<AssemblyDR> assembly=null; 
    Vector<Vector<String>> data = null;
    Vector<String> columnNames = null;
    Vector<String> columnNames2 = null;   
    private String enqId;
    private String revNo;
    
    public EnquiryDetails() {
        initComponents();
    }
    
    public void loadTable(String enqId,String enqNo,String custName,String revNo)
    {
        this.enqId=enqId;
        this.revNo=revNo;
        jLabel1.setText(enqNo);
        jLabel4.setText(custName);
        
        assembly=new ArrayList<AssemblyDR>();
        data =new Vector<Vector<String>>();
        columnNames=new Vector<String>();
        columnNames2=new Vector<String>();
       
        columnNames.add("assly_no");
        columnNames2.add("AssemblyNo");
        columnNames.add("assembly_desc");
        columnNames2.add("Assembly Desc");
        columnNames.add("quantity");
        columnNames2.add("Quantity");
        columnNames.add("drwg_no");
        columnNames2.add("Drwg No");
        columnNames.add("drwg_rev_no");
        columnNames2.add("Drwg rev No");
        columnNames.add("drwg_rev_date");
        columnNames2.add("Drwg rev Date");
        
        String addEmpAPICall="assemblies?ref_enq_id="+enqId;
        System.err.println(addEmpAPICall);

        String result2=WebAPITester.prepareWebCall ( addEmpAPICall, StaticValues.getHeader ()   , ""); 

        if ( result2!= null ) 
        {
            HashMap<String, Object> map2=new HashMap<String, Object>();
            JSONObject jObject2 = new JSONObject( result2 );
            Iterator<?> keys2 =jObject2.keys();

            while( keys2.hasNext() ){
                String key = (String)keys2.next();
                Object value = jObject2.get ( key ) ; 
                map2.put(key, value);
            }
            JSONObject st1 = (JSONObject) map2.get ( "data" );
           
            JSONArray records1 = st1.getJSONArray ( "records"); 
            
            JSONObject assly = null;
            for( int i1=0; i1<records1.length (); i1++ )
            {
                Vector<String> vector =new Vector<String>();
                assly = records1.getJSONObject ( i1);
                String assId=assly.get("assly_id").toString();
                String assNo=assly.get("assly_no").toString();     
                String assDesc=assly.get("assembly_desc").toString();
                String assQuan=assly.get("quantity").toString();
                String drwgNo=assly.get("drwg_no").toString();
                String drwgRevNo=assly.get("drwg_rev_no").toString();
                String drwgRevDate=assly.get("drwg_rev_date").toString();
                
                assembly.add(new AssemblyDR(assId, assNo, assDesc, assQuan, drwgNo, drwgRevNo, drwgRevDate));
                vector.add(assNo);
                vector.add(assDesc);
                vector.add(assQuan);
                vector.add(drwgNo);
                vector.add(drwgRevNo);
                vector.add(drwgRevDate);
                
                data.add(vector);
            }
            jTable1.setModel(new DefaultTableModel (data,columnNames2));
        }
    }
    
    public List getList()
    {
        List<String> list=new ArrayList<String>();
        int index=jTable1.getSelectedRow();
        list.add(jLabel1.getText());
        list.add(assembly.get(index).getAssNo());
        list.add(assembly.get(index).getAssDesc());
        list.add(assembly.get(index).getDrwgNo());
        list.add(assembly.get(index).getQuant());
        list.add(jLabel4.getText());
        list.add(enqId);
        list.add(revNo);
        list.add(assembly.get(index).getDrwgRevNo());
        list.add(assembly.get(index).getDrwgDate());
        list.add(assembly.get(index).getAssId());
        return list;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1);
        jScrollPane1.setBounds(31, 55, 610, 245);
        add(jLabel1);
        jLabel1.setBounds(110, 20, 80, 26);

        jLabel2.setText("Enquiry No :-");
        add(jLabel2);
        jLabel2.setBounds(40, 20, 71, 26);

        jLabel3.setText("Custtomer Name :-");
        add(jLabel3);
        jLabel3.setBounds(400, 20, 100, 26);
        add(jLabel4);
        jLabel4.setBounds(500, 20, 140, 26);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
