/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trixware.erp.prodezydesktop.quotation;

import javax.swing.ButtonGroup;
import javax.swing.JCheckBox;
import javax.swing.JLabel;

/**
 *
 * @author Rajesh
 */
public class FeasibilityPanel extends javax.swing.JPanel {

    private String conditionStr ;
    private int conditionInt ;
    private boolean selected ;
    
    /**
     * Creates new form PartDetailsPanel
     */
    public FeasibilityPanel ( int no, String condition  , boolean selection) {
        initComponents ();
        this.conditionStr = condition;
        this.conditionInt = no;
        this.selected = selection;
        jLabel2.setText( condition);
        jLabel3.setText( no+"" );        
        jCheckBox1.setSelected ( selection);
    }

    public FeasibilityPanel () {
        initComponents ();
    }

    public String getConditionStr () {
        return conditionStr;
    }

    public void setConditionStr ( String conditionStr ) {
        jLabel3.setText( conditionStr );
        this.conditionStr = conditionStr;
    }

    public int getConditionInt () {
        return conditionInt;
    }

    public void setConditionInt ( int conditionInt ) {
        jLabel2.setText ( conditionInt+"");
        this.conditionInt = conditionInt;
    }

    public boolean isSelected () {
        return jCheckBox1.isSelected ();
    }

    public void setSelected ( boolean selected ) {
        jCheckBox1.setSelected ( selected );
        this.selected = selected;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings( "unchecked" )
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(500, 50));
        setLayout(null);

        jLabel2.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        add(jLabel2);
        jLabel2.setBounds(40, 0, 550, 50);

        jLabel3.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("srno");
        add(jLabel3);
        jLabel3.setBounds(3, 6, 30, 40);

        jCheckBox1.setBackground(new java.awt.Color(255, 255, 255));
        add(jCheckBox1);
        jCheckBox1.setBounds(600, 10, 30, 40);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        if(  jCheckBox1.isSelected ()  ){
            jCheckBox1.setSelected ( false );
        }else{
            jCheckBox1.setSelected ( true );
        }
    }//GEN-LAST:event_jLabel2MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
