/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trixware.erp.prodezydesktop.quotation;

import java.util.ArrayList;

/**
 *
 * @author Akshay
 */
public class ProcessUnits extends javax.swing.JPanel {

    /**
     * Creates new form ProcessUnits
     */
    ArrayList<String[]> units;
    public ProcessUnits(ArrayList<String[]> units) {
        initComponents();
        this.units=units;
        jComboBox1.removeAllItems();

        for(String[] unit:units)
        {
             jComboBox1.addItem(unit[1]);
        }
    }

    public String getUnitId()
    {
        int index=jComboBox1.getSelectedIndex();
        return units.get(index)[0]; 
    }

    public String getUnitName()
    {
        return jComboBox1.getSelectedItem().toString();
    }
    public void setUnitName(String unitName)
    {
        jComboBox1.setSelectedItem(unitName);
    }    
    public String getUnitCost()
    {
        return jTextField1.getText();
    }
    public void setUnitCost(String unitCost)
    {
        jTextField1.setText(unitCost);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(jComboBox1);
        jComboBox1.setBounds(20, 10, 130, 31);

        jTextField1.setText(" ");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        add(jTextField1);
        jTextField1.setBounds(260, 10, 70, 30);

        jLabel1.setText("<html>Rate/Unit <br>in Rs</html>");
        add(jLabel1);
        jLabel1.setBounds(180, 10, 60, 28);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
