/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trixware.erp.prodezydesktop.Utilities;

import trixware.erp.prodezydesktop.components.ButtonForm;
import trixware.erp.prodezydesktop.components.PasswordInputForm;
import trixware.erp.prodezydesktop.components.ProgressDialog;
import trixware.erp.prodezydesktop.components.TextInputForm;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import trixware.erp.prodezydesktop.examples.HomeScreen;

/**
 *
 * @author Rajesh
 */
public class LoginForm extends javax.swing.JPanel {

  //  public LoginDialog loginDlg = null ;
    private boolean succeeded;
    TextInputForm userName ;
    
    PasswordInputForm  password ;
    
    
    /**
     * Creates new form LoginForm
     */
    public LoginForm () {
        initComponents ();
        
        
        
      //  setLayout ( new GridLayout (1, 2));
        
         userName = new TextInputForm ("Username", true, "Username is mandatoy to complete login action !") ;
        userName.setBounds( 20, 10 , 260, 64  )  ;
        add( userName );
        
         password = new PasswordInputForm ("Password", true, "Password is mandatoy to complete login action !") ;
        password.setBounds( 20, 74 , 260, 64  )  ;
        add( password );
        
        ButtonForm submit = new ButtonForm ("Log In", "Username and password are mandatory") ;
        add( submit ) ;
        submit.setBounds( 20, 138 , 260, 64  )  ;
        
        submit.AddActionListener(       login       );
        
    }
    
    
    
    boolean loggedIn = false;
    static ProgressDialog progress = new ProgressDialog( null ) ;
    Thread getTableAndFilesContent = null ;
    public boolean showDialog(){
         
        
        progress.updateTitle ( "Logging In" );
        progress.updateMessage ( "<html>Please wait...<br>Loggin you in the system</htm>");
        
        getTableAndFilesContent = new Thread(){
            public void run(){
                try{
                sleep( 1000);
                }catch( InterruptedException ee ){
                    
                }
            loggedIn =  Login.authenticate(   userName.getText(), password.getText () ) ;
            }
        };
        getTableAndFilesContent.start();
        progress.openProgressWindow ();
        
        return loggedIn ;
    }
    
    public static boolean hideDialog(){
        progress.closeProgressWindow ();
        return true ;
    }
    
    
    
    ActionListener login = new ActionListener(){
        @Override
        public void actionPerformed ( ActionEvent e ) {
            
            if(  !   userName.getText().equals ( "") &&  !password.getText ().equals ( "")   ){
            
             //boolean loggedIn = Login.authenticate(   userName.getText(), password.getText () ) ;
             boolean loggedIn = showDialog () ;
             
            
             if ( loggedIn ) {
                 
                    
                 //JOptionPane.showMessageDialog(null,
                 //       "Hi " + "" + "! You have successfully logged in.",
                 //       "Login",
                 //       JOptionPane.INFORMATION_MESSAGE);
                    
                    HomeScreen.home.jLabel5.setVisible ( true );
                    
                    succeeded = true;
                  
                } else {
                 
                    
                     JOptionPane.showMessageDialog(null,
                            "Invalid username or password",
                             "Login",
                            JOptionPane.ERROR_MESSAGE);
                    // reset username and password
                    succeeded = false; 
                }
            }
        }
    };

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings( "unchecked" )
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
