/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package trixware.erp.prodezydesktop.Utilities;

import trixware.erp.prodezydesktop.Model.ShiftDR;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.DefaultListModel;
import javax.swing.table.DefaultTableModel;
import trixware.erp.prodezydesktop.Model.ShiftDR;

/**
 *
 * @author Rajesh
 */
public class ShiftsList_old extends javax.swing.JPanel {

    ResultSet result = null;
    
    ArrayList<ShiftDR> shifts = new ArrayList<ShiftDR>();
    DefaultListModel<String> list =null ;
    
   private int selectedShiftId = 0;
    String selectedShiftStr = "";
    
    /** Creates new form ProdDataConformationScreen */
    public ShiftsList_old() {
        initComponents();
        
        list = new DefaultListModel<>();
        
        ShiftDR sdr1  = new ShiftDR() ;
        sdr1.SHIFT_ID  = 1 ;
        sdr1.SHIFT_NAME = "Day" ;
        shifts.add( sdr1);
        
         sdr1  = new ShiftDR() ;
        sdr1.SHIFT_ID  = 2 ;
        sdr1.SHIFT_NAME = "Night" ;
        
        shifts.add( sdr1);
        
         sdr1  = new ShiftDR() ;
        sdr1.SHIFT_ID  = 3 ;
        sdr1.SHIFT_NAME = "General" ;
        shifts.add( sdr1);
        
        list.addElement ("Day" );
        list.addElement ("Night" );
        list.addElement ("General" );
  
        jList1.setModel(list);
    }
    
    public static DefaultTableModel buildTableModel ( ResultSet rs )
            throws SQLException {

        ResultSetMetaData metaData = rs.getMetaData ();

        // names of columns
        Vector<String> columnNames = new Vector<String> ();
        int columnCount = metaData.getColumnCount ();
        for ( int column = 1 ; column <= columnCount ; column ++ ) {
            columnNames.add ( metaData.getColumnName ( column ) );
        }

        // data of the table
        Vector<Vector<Object>> data = new Vector<Vector<Object>> ();
        while ( rs.next () ) {

            Vector<Object> vector = new Vector<Object> ();
            for ( int columnIndex = 1 ; columnIndex <= columnCount ; columnIndex ++ ) {
                vector.add ( rs.getObject ( columnIndex ) );
            }
            data.add ( vector );
        }

        return new DefaultTableModel ( data , columnNames );

           
        }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1150, 500));
        setPreferredSize(new java.awt.Dimension(1100, 500));
        setLayout(null);

        jButton1.setText("Select");
        jButton1.setOpaque(false);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(0, 190, 100, 32);

        jButton2.setText("Cancel");
        jButton2.setOpaque(false);
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        add(jButton2);
        jButton2.setBounds(100, 190, 100, 32);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Select Shift");
        add(jLabel1);
        jLabel1.setBounds(0, 0, 200, 30);

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(jList1);

        add(jScrollPane2);
        jScrollPane2.setBounds(0, 30, 200, 160);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        
      //  JOptionPane.showMessageDialog ( null, jList1.getSelectedValue ());
        selectedShiftId = jList1.getSelectedIndex ();
        selectedShiftStr = jList1.getSelectedValue () ;
        
      //  SingleProcessDE_Form.dialog.dispose ();
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        
       // SingleProcessDE_Form.dialog.dispose ();
    }//GEN-LAST:event_jButton2MouseClicked

    public int  getSelectedShiftId(){
        return selectedShiftId ;
    }

     public String getSelectedShiftStr(){
        return selectedShiftStr ;
    }
     
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables

}
