/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package trixware.erp.prodezydesktop.Utilities;

import java.awt.BorderLayout;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.table.DefaultTableModel;
import trixware.erp.prodezydesktop.Model.TimeLossModel;
import trixware.erp.prodezydesktop.components.TimeLossDetailPanel;

/**
 *
 * @author Rajesh
 */
public class TimeLossList_old extends javax.swing.JPanel {

    ResultSet result = null;
    
    public  ArrayList<TimeLossDetailPanel> timeLossList = null ;
    private  ArrayList<TimeLossModel> timeLossDetailList = new ArrayList<TimeLossModel>() ;
    
    /** Creates new form ProdDataConformationScreen */
    public TimeLossList_old() {
        initComponents();
    
        
            TimeLossReasonList panel = new TimeLossReasonList (  );
            panel.setBounds ( 10 , 50 , 360 , 280 );
            panel.setBackground ( Color.white );
            add ( panel );
            
        
    }
    
    public static DefaultTableModel buildTableModel ( ResultSet rs )
            throws SQLException {

        ResultSetMetaData metaData = rs.getMetaData ();

        // names of columns
        Vector<String> columnNames = new Vector<String> ();
        int columnCount = metaData.getColumnCount ();
        for ( int column = 1 ; column <= columnCount ; column ++ ) {
            columnNames.add ( metaData.getColumnName ( column ) );
        }

        // data of the table
        Vector<Vector<Object>> data = new Vector<Vector<Object>> ();
        while ( rs.next () ) {

            Vector<Object> vector = new Vector<Object> ();
            for ( int columnIndex = 1 ; columnIndex <= columnCount ; columnIndex ++ ) {
                vector.add ( rs.getObject ( columnIndex ) );
            }
            data.add ( vector );
        }

        return new DefaultTableModel ( data , columnNames );

           }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        setMinimumSize(new java.awt.Dimension(1150, 500));
        setPreferredSize(new java.awt.Dimension(1100, 500));
        setLayout(null);

        jButton1.setText("Submit");
        jButton1.setOpaque(false);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(100, 332, 100, 40);

        jButton2.setText("Cancel");
        jButton2.setOpaque(false);
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        add(jButton2);
        jButton2.setBounds(200, 332, 100, 40);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Add time in minutes for applicable timeloss reasons");
        add(jLabel1);
        jLabel1.setBounds(0, 0, 410, 30);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        TimeLossModel tlm = null ;
        
        for( int i=0; i<timeLossList.size (); i++  ){
            
            tlm = new TimeLossModel();
            if( timeLossList.get(i).getMinutes ()>0 ){
                tlm.setMinutes ( timeLossList.get(i).getMinutes () );
                tlm.setId (  timeLossList.get(i).getTRLid () );
                tlm.setReason (  timeLossList.get(i).getReasonStr ());
                timeLossDetailList.add(  tlm );
            }
        }
        
        
        TimeLossModel tlm2 = null ;
        StringBuilder sb = new StringBuilder();
        for( int i=0; i<timeLossDetailList.size (); i++  ){
                tlm2 = timeLossDetailList.get(i);
                
                sb.append ( tlm2.getId () );
                sb.append ( tlm2.getReason ());
                sb.append ( tlm2.getMinutes ());
                sb.append ( "\n");
         }
        
     //   JOptionPane.showMessageDialog( null, sb.toString () );
        
        
  //      SingleProcessDE_Form.dialog2.dispose ();
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        
        
   //     SingleProcessDE_Form.dialog2.dispose ();
    }//GEN-LAST:event_jButton2MouseClicked

    public ArrayList<TimeLossModel> getTimeLossList(){
        return timeLossDetailList;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    
     class TimeLossReasonList extends JPanel {

        private JPanel panel;

        private JScrollPane scroll;
        private JButton btnAddType;

        
   

//    public ArrayList<RMQtyPanel> rmBomList = null ;
        public TimeLossReasonList (   ) {
            // getContentPane().setLayout(new BorderLayout());       

            setLayout ( new BorderLayout () );

            panel = new JPanel ();
            panel.setLayout ( new BoxLayout ( panel , BoxLayout.Y_AXIS ) );
            scroll = new JScrollPane ( panel ,
                    JScrollPane.VERTICAL_SCROLLBAR_ALWAYS ,
                    JScrollPane.HORIZONTAL_SCROLLBAR_NEVER );

            add ( scroll , BorderLayout.CENTER );

            setVisible ( true );

            TimeLossDetailPanel pane = null;

          
                timeLossList = new ArrayList<TimeLossDetailPanel> ();

                
                    pane = new TimeLossDetailPanel ();
                    pane.setTRLid (  1   );
                    pane.setReasonStr ( "Person Not Available" );
                    pane.setMinutes (  0 );
                     panel.add ( pane );
                    panel.revalidate ();
                    timeLossList.add ( pane );
                    
                    pane = new TimeLossDetailPanel ();
                    pane.setTRLid (  2   );
                    pane.setReasonStr ( "No Electricity" );
                    pane.setMinutes (  0 );
                     panel.add ( pane );
                    panel.revalidate ();
                    timeLossList.add ( pane );
                    
                    pane = new TimeLossDetailPanel ();
                    pane.setTRLid (  3  );
                    pane.setReasonStr ( "Setup Time" );
                    pane.setMinutes (  0 );
                     panel.add ( pane );
                    panel.revalidate ();
                    timeLossList.add ( pane );
                    
                    pane = new TimeLossDetailPanel ();
                    pane.setTRLid (  4   );
                    pane.setReasonStr ( "Machine Failure" );
                    pane.setMinutes (  0 );
                     panel.add ( pane );
                    panel.revalidate ();
                    timeLossList.add ( pane );
                    
                    pane = new TimeLossDetailPanel ();
                    pane.setTRLid (  5   );
                    pane.setReasonStr ( "Other" );
                    pane.setMinutes (  0 );
                    
                   
                    panel.add ( pane );
                    panel.revalidate ();
                    
                    //   System.out.println ( pane.getRmid ()+" "+pane.getRMName ());
                    
                    timeLossList.add ( pane );
                }
       }
    }
     
     
    



