/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package components;

import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author Rajesh
 */
public class ComboBoxJTextFieldItem extends javax.swing.JPanel {

    private String reason;
    private int minutes ;
    
    
    /**
     * Creates new form ComboBoxJTextFieldItem
     */
    public ComboBoxJTextFieldItem () {
        this.readItem = new FocusListener(){
            @Override
            public void focusGained ( FocusEvent e ) {
                jTextField1.requestFocus ();
            }
            
            @Override
            public void focusLost ( FocusEvent e ) {
              //  jTextField1.rem
            }
            
        };
        initComponents ();
    }

    public ComboBoxJTextFieldItem ( JLabel jLabel1 , JTextField jTextField1 ) {
        this.readItem = new FocusListener(){
            @Override
            public void focusGained ( FocusEvent e ) {
                jTextField1.requestFocus ();
            }
            
            @Override
            public void focusLost ( FocusEvent e ) {
                
            }
            
        };
        this.jLabel1 = jLabel1;
        this.jTextField1 = jTextField1;
        
        jTextField1.setFocusable ( true );
    }

    
    FocusListener readItem ;
    
    
    public String getReason () {
        return reason;
    }

    public void setReason ( String reason ) {
        this.reason = reason;
        jLabel1.setText(  reason );
    }

    public int getMinutes () {
        return Integer.parseInt ( jTextField1.getText() );
    }

    public void setMinutes ( int minutes ) {
        this.minutes = minutes;
        jTextField1.setText( minutes+"" ) ;
    }

   
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings( "unchecked" )
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setNextFocusableComponent(jTextField1);
        setPreferredSize(new java.awt.Dimension(259, 25));
        setLayout(null);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        add(jLabel1);
        jLabel1.setBounds(6, 0, 170, 25);
        add(jTextField1);
        jTextField1.setBounds(180, 0, 60, 24);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
