/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trixware.erp.prodezydesktop.components;

import java.awt.Color;
import java.util.ArrayList;
import javax.swing.BoxLayout;
import javax.swing.JPanel;
import javax.swing.JScrollPane;

/**
 *
 * @author Rajesh
 */
public class DeliveryScheduleForm extends javax.swing.JPanel {

    JPanel listPanel = null ;
    JScrollPane jScrollPane1 = null ;
    
    ArrayList< DeliverySchDetailPanel  >  shcdPanelList = new ArrayList< DeliverySchDetailPanel  > () ;
    public ArrayList< DeliverySchDetailPanel  >  filledShcdPanelList = new ArrayList< DeliverySchDetailPanel  > () ;
     
    /**
     * Creates new form DeliveryScheduleForm
     */
    public DeliveryScheduleForm () {
        initComponents ();
        
        listPanel = new JPanel() ;
        listPanel.setBackground( Color.white  );
        listPanel.setBounds( 0,0, 250, 5 ) ;
        
        listPanel.setLayout ( new BoxLayout ( listPanel , BoxLayout.Y_AXIS ) );
        //listPanel.setLayout (null );
        
        jScrollPane1 = new JScrollPane( listPanel, 
                JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED, 
                JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED   ) ;
        
        jScrollPane1.setBounds(  20, 50, 400, 280  ) ;
        
        add(jScrollPane1);
        
       dp = new DeliverySchDetailPanel ();
       dp.setBounds ( 0, 0, 250, 50);
       listPanel.add(dp);
       shcdPanelList.add(   dp   ) ;
        
        revalidate ();
        repaint ();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings( "unchecked" )
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        jButton2.setText("jButton2");

        setLayout(null);

        jButton1.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
        jButton1.setText("Submit Schedule & Close");
        jButton1.setOpaque(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(210, 340, 180, 32);

        jButton3.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
        jButton3.setText("Add New Row");
        jButton3.setOpaque(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3);
        jButton3.setBounds(280, 10, 110, 32);

        jButton4.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
        jButton4.setText("Discard & Close");
        add(jButton4);
        jButton4.setBounds(70, 340, 140, 32);
    }// </editor-fold>//GEN-END:initComponents

    DeliverySchDetailPanel dp = null ;
    int totalPanels = 1 ;
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        dp = new DeliverySchDetailPanel ();
        dp.setBounds ( 0, (totalPanels)*40, 250, 50);
        listPanel.add(dp);
     
        shcdPanelList.add(   dp   ) ;
        
        totalPanels++ ;
        revalidate ();
        repaint ();
    
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        for (   int i=0; i<shcdPanelList.size () ; i++   )  {
            if(  shcdPanelList.get ( i ).getQty () > 0.0   ){
                filledShcdPanelList.add(  shcdPanelList.get ( i ) ) ;
            }
        }      
        
    }//GEN-LAST:event_jButton1ActionPerformed

    
    public ArrayList< DeliverySchDetailPanel  > getSchedule(){
        return filledShcdPanelList ;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    // End of variables declaration//GEN-END:variables
}
