/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trixware.erp.prodezydesktop.components;

import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JTextField;

/**
 *
 * @author Rajesh
 */
public class DeliverySchDetailPanel extends javax.swing.JPanel {

    
    String date ;
    double qty ;
    
    public DeliverySchDetailPanel () {
        initComponents ();
        
        jTextField1.addKeyListener ( k );
        jTextField1.addFocusListener ( f2 );        
    }

    public String getDate () {
        return new SimpleDateFormat( "yyyy-MM-dd HH:mm:ss" ).format(  dateChooserCombo1.getSelectedDate ().getTime ()  );
    }

    public void setDate ( Calendar date ) {
        dateChooserCombo1.setSelectedDate ( date );
        this.date = new SimpleDateFormat( "yyyy-MM-dd HH:mm:ss" ).format(  date.getTime ()  );
    }

    public double getQty () {
        String qty = jTextField1.getText().toString ().trim();
        int qtyInt;
        double qtyDouble ;
        try{
            qtyInt = Integer.parseInt( qty );
            setQty ( qtyInt*1.00 );
            return qtyInt*1.00 ;
        }catch( NumberFormatException e){
            qtyDouble = Double.parseDouble ( qty ) ;
            setQty ( qtyDouble );
            return qtyDouble ;
        }       
      //  return  jTextField1.getText().trim() ;
    }

    public void setQty ( double qty ) {
        this.qty = qty;
        jTextField1.setText( ""+qty );
    }
    
    /*This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor */
    @SuppressWarnings( "unchecked" )
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dateChooserCombo1 = new datechooser.beans.DateChooserCombo();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(260, 50));
        setLayout(null);

        dateChooserCombo1.setFormat(2);
        add(dateChooserCombo1);
        dateChooserCombo1.setBounds(10, 5, 155, 30);

        jLabel1.setOpaque(true);
        add(jLabel1);
        jLabel1.setBounds(0, 0, 0, 0);
        add(jLabel2);
        jLabel2.setBounds(10, 5, 150, 0);

        jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField1FocusGained(evt);
            }
        });
        add(jTextField1);
        jTextField1.setBounds(190, 5, 50, 30);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1FocusGained

    KeyListener k = new KeyListener () {
        @Override
        public void keyTyped ( KeyEvent e ) {
           char enter = e.getKeyChar();
           String dot = Character.toString ( enter );
           
            if (!(Character.isDigit(enter))   && ! dot.equals ( "." )  ) {
                e.consume();
            }
        }

        @Override
        public void keyPressed ( KeyEvent e ) {
        }

        @Override
        public void keyReleased ( KeyEvent e ) {
        }
    };
    
    FocusListener f2 = new FocusListener () {
        @Override
        public void focusGained ( FocusEvent e ) {
//            throw new UnsupportedOperationException ( "Not supported yet." ); //To change body of generated methods, choose Tools | Templates.
            JTextField jcb = ( JTextField ) e.getSource ();    
            jcb.setText("");
        }

        @Override
        public void focusLost ( FocusEvent e ) {
        //    throw new UnsupportedOperationException ( "Not supported yet." ); //To Search Google or type URL
//change body of generated methods, choose Tools | Templates.
            JTextField jcb = ( JTextField ) e.getSource ();    
            String x = jcb.getText().trim ();
            
            if(x.equalsIgnoreCase ( "")){
                x = "0";
            }
            
            try{    
                int num  = Integer.parseInt( String.valueOf( jcb.getText().toString() ) );
                    if( num<0  ){
                     jcb.setText(x);
                }
            }catch(NumberFormatException ex1){
            }
        }
    };

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private datechooser.beans.DateChooserCombo dateChooserCombo1;
    public static javax.swing.JLabel jLabel1;
    public static javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
