/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trixware.erp.prodezydesktop.components;

import trixware.erp.prodezydesktop.Model.EmployeeDR_User;
import trixware.erp.prodezydesktop.Model.StaticValues;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.io.UnsupportedEncodingException;
import java.net.URLEncoder;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import trixware.erp.prodezydesktop.masters.Create_User;
import org.json.JSONArray;
import org.json.JSONObject;
import trixware.erp.prodezydesktop.web_services.WebAPITester;

/**
 *
 * @author mayur
 */
public class dialogCreateUserPanel extends javax.swing.JPanel {

    boolean mandatory = false; 
    boolean showError = false ;
    String labelValue, textValue, errorValue ;
    
    int empid=0;
    String empname="",pwd="",repassword="",usernm1="",emp_name="";
    
    ArrayList<EmployeeDR_User> employees=null;
    
    /**
     * Creates new form TextInputForm
     */
    public dialogCreateUserPanel () {
        initComponents ();
       
    }

    public dialogCreateUserPanel (int id,  String  name) {
        initComponents ();
      
        loadcontent();
        empid=id;
        empname=name;
        
        emp_name=jLabel5.getText();
        usernm1=usernm.getText();
        jLabel6.setText(empid+"");
        jLabel5.setText(empname);
        pwd=password.getText();
        repassword=repwd.getText();
        
        
    }
    
    public void loadcontent()
    {
             String addEmpAPICall = "employees";
                String result2 =  WebAPITester.prepareWebCall ( addEmpAPICall, StaticValues.getHeader ()   , "");
                  System.out.println(result2);
                if( !  result2.contains(  "not found"   )  )
                {
                    if ( result2!= null ) 
                    {
                          HashMap<String, Object> map = new HashMap<String, Object>();
                            JSONObject jObject = new JSONObject( result2 );
                            Iterator<?> keys = jObject.keys();

                            while( keys.hasNext() )
                            {
                                String key = (String)keys.next();
                                Object value = jObject.get ( key ) ; 
                                map.put(key, value);
                            }

          
                            JSONObject st = (JSONObject) map.get ( "data" );
                            JSONArray records = st.getJSONArray ( "records");

                            JSONObject emp = null;
                            employees = new ArrayList<EmployeeDR_User> ();
                            for ( int i = 0 ; i < records.length () ; i ++ ) 
                            {
                                  emp = records.getJSONObject ( i);
                                EmployeeDR_User   empdr = new EmployeeDR_User ();
                                empdr.EMP_ID =  emp.getInt("EmployeePK" ) ;
                                empdr.EMP_NAME = emp.getString ( "EMP_NAME" );
                                empdr.DEPART_ID = emp.getInt("DEPARTMENTID");
                                empdr.ROLE_ID = emp.getString("ROLE");
                                employees.add ( empdr );
                                //jComboBox1.addItem ( emp.getString ( "EMP_NAME" ) );    
                             }
                    }
        
                }    
                
                if(employees.size()==0)
                {
                    jButton2.setEnabled(false);
                    JOptionPane.showMessageDialog ( null , "Employee not found to Create user. Please add at least 1 employee " );        
                }
              
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings( "unchecked" )
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        repwd = new javax.swing.JTextField();
        password = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        usernm = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(260, 64));
        setLayout(null);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Create User ");
        add(jLabel4);
        jLabel4.setBounds(250, 10, 220, 30);

        jLabel1.setText("Re-password");
        add(jLabel1);
        jLabel1.setBounds(100, 210, 100, 30);

        jLabel2.setText("Employee Name");
        add(jLabel2);
        jLabel2.setBounds(100, 70, 100, 30);

        jLabel3.setText("Password");
        add(jLabel3);
        jLabel3.setBounds(100, 160, 100, 30);

        jLabel5.setText("username");
        add(jLabel5);
        jLabel5.setBounds(260, 60, 230, 40);
        add(repwd);
        repwd.setBounds(260, 210, 230, 30);
        add(password);
        password.setBounds(260, 160, 230, 30);

        jButton1.setText("Cancel");
        add(jButton1);
        jButton1.setBounds(350, 280, 120, 40);

        jButton2.setText("Create User");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2);
        jButton2.setBounds(120, 280, 120, 40);
        add(jLabel6);
        jLabel6.setBounds(270, 80, 0, 0);

        jLabel7.setText("Username");
        add(jLabel7);
        jLabel7.setBounds(100, 110, 80, 30);
        add(usernm);
        usernm.setBounds(260, 110, 230, 30);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        pwd = password.getText();
        repassword = repwd.getText();
        
         if( !usernm1.contains ( " ")  && !usernm1.contains( " " ) )
           {
              String[] names ;
              String createUserAPICall = null;
               if(  emp_name.contains(" "))
                 {
                  names = emp_name.split(" ");
            /*        try {
                     createUserAPICall = "useradd?username="+URLEncoder.encode(usernm1,"UTF-8")+"&password="+URLEncoder.encode(pwd,"UTF-8")+"&password_confirmation="+URLEncoder.encode(repassword,"UTF-8")+"&acc_expiry_option=n&email=example@example.com&firstname="+URLEncoder.encode(names[0],"UTF-8")+"&lastname="+URLEncoder.encode(names[1],"UTF-8")+"&email=example@example.com&role_id="+URLEncoder.encode(role+"","UTF-8")+"&user_type=operator&contactno=&theme=&profile_photo=&department_id=4,3&designation_id="+URLEncoder.encode(department_id+"","UTF-8")+"&acc_expiry_option=&expiry_date=&ref_emp_id="+URLEncoder.encode(""+Emp_id,"UTF-8");                    
                    } catch (UnsupportedEncodingException ex) 
                        {
                         Logger.getLogger(Create_User.class.getName()).log(Level.SEVERE, null, ex);
                        }
                  }else
                   {
                    try {
                      createUserAPICall = "useradd?username="+URLEncoder.encode(usernm1,"UTF-8")+"&password="+URLEncoder.encode(pwd,"UTF-8")+"&password_confirmation="+URLEncoder.encode(repassword,"UTF-8")+"&acc_expiry_option=n&email=example@example.com&firstname="+URLEncoder.encode(emp_name,"UTF-8")+"&lastname="+URLEncoder.encode(emp_name,"UTF-8")+"&email=example@example.com&role_id="+URLEncoder.encode(role+"","UTF-8")+"&user_type=operator&contactno=&theme=&profile_photo=&department_id=4,3&designation_id="+URLEncoder.encode(department_id+"","UTF-8")+"&acc_expiry_option=&expiry_date=&ref_emp_id="+URLEncoder.encode(""+Emp_id,"UTF-8");
                        } catch (UnsupportedEncodingException ex) {
                            Logger.getLogger(Create_User.class.getName()).log(Level.SEVERE, null, ex);
                                    }*/
                                }
                              
                       String  result2 =  WebAPITester.prepareWebCall ( createUserAPICall , StaticValues.getHeader ()   , "");
                           System.out.println ( "" + result2 );  
                         JOptionPane.showMessageDialog ( null , result2);
                         
                        
                      }else{
                                JOptionPane.showMessageDialog ( null , "Please enter appropriate username and password " );        
                            }
                         usernm.setText ( "" );
                         password.setText ( "" );
                         repwd.setText("");       
        
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField password;
    private javax.swing.JTextField repwd;
    private javax.swing.JTextField usernm;
    // End of variables declaration//GEN-END:variables
}
