/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trixware.erp.prodezydesktop.components;

import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import javax.swing.JTextField;

/**
 *
 * @author Rajesh
 */
public class IntegerInputField extends javax.swing.JPanel {

    boolean mandatory = false; 
    boolean showError = false ;
    String labelValue, textValue, errorValue ;
    
    
    /**
     * Creates new form TextInputForm
     */
    public IntegerInputField () {
        initComponents ();
        
        jLabel3.setVisible ( false );
        jTextField1.addFocusListener ( f2 );
        jTextField1.addKeyListener ( k );
    }

    public IntegerInputField (String labelVal,  boolean isMandatory, String errorString) {
        initComponents ();
        mandatory = isMandatory ;
        jLabel2.setVisible ( mandatory );
        errorValue = errorString ;
        jLabel3.setToolTipText ( errorValue );
        jLabel1.setText( labelVal  ) ;
        jLabel3.setVisible ( false );
                jTextField1.addFocusListener ( f2 );
        jTextField1.addKeyListener ( k );
    }
    
   

    FocusListener valueListener = new FocusListener () {
        @Override
        public void focusGained ( FocusEvent e ) {
            JTextField jcb = ( JTextField ) e.getSource ();
            if( ! jcb.getText ().equals ( "")){
                jcb.selectAll ();
            }
            showError  = false ;
            jLabel3.setText ("" );
            jLabel3.setVisible ( false );
        }

        @Override
        public void focusLost ( FocusEvent e ) {
            JTextField jcb = ( JTextField ) e.getSource ();
            if( mandatory ){
                if(  jcb.getText ().equals ( "" )){
                    showError  = true ;
                    jLabel3.setText ( errorValue );
                    jLabel3.setVisible ( true );
                }else{
                    showError  = false ;
                    jLabel3.setText ( "" );
                    jLabel3.setVisible ( false );
                }
            }
        }
    };
    
    
    public String getText(){
        return jTextField1.getText ().trim () ;
    }
    
    public void setText(String value){
        jTextField1.setText( value );
        jTextField1.revalidate ();
        jTextField1.repaint ();
    }
    
    public void setEnabled( boolean value ){
        jTextField1.setEnabled(value);
    }
    
    public void setEditable( boolean value ){
        jTextField1.setEditable(value);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings( "unchecked" )
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(260, 64));
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
        jLabel1.setText("Label Name");
        add(jLabel1);
        jLabel1.setBounds(14, 0, 230, 16);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("*");
        add(jLabel2);
        jLabel2.setBounds(0, 0, 10, 19);
        add(jTextField1);
        jTextField1.setBounds(10, 17, 250, 30);

        jLabel3.setFont(new java.awt.Font("Leelawadee UI", 0, 10)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        add(jLabel3);
        jLabel3.setBounds(0, 50, 260, 15);
    }// </editor-fold>//GEN-END:initComponents

       KeyListener k = new KeyListener () {
        @Override
        public void keyTyped ( KeyEvent e ) {
           char enter = e.getKeyChar();
            if (!(Character.isDigit(enter))) {
                e.consume();
            }
            
        }

        @Override
        public void keyPressed ( KeyEvent e ) {
        }

        @Override
        public void keyReleased ( KeyEvent e ) {
        }
    };
    
    FocusListener f2 = new FocusListener () {
        @Override
        public void focusGained ( FocusEvent e ) {
//            throw new UnsupportedOperationException ( "Not supported yet." ); //To change body of generated methods, choose Tools | Templates.
            JTextField jcb = ( JTextField ) e.getSource ();    
           // jcb.setText("");
            
            if( ! jcb.getText ().equals ( "")){
                jcb.selectAll ();
            }
            showError  = false ;
            jLabel3.setText ("" );
            jLabel3.setVisible ( false );
        }

        @Override
        public void focusLost ( FocusEvent e ) {
        //    throw new UnsupportedOperationException ( "Not supported yet." ); //To Search Google or type URL
//change body of generated methods, choose Tools | Templates.
            JTextField jcb = ( JTextField ) e.getSource ();    
            String x = jcb.getText().trim ();
            if(x.equalsIgnoreCase ( "")){
                x = "0";
            }
            
            try{    
                int num  = Integer.parseInt( String.valueOf( jcb.getText().toString() ) );
                    if( num<0  ){
                     jcb.setText(x);
                    //evt.consume ();
                }
            }catch(NumberFormatException ex1){
                    jcb.setText(x);
            }
            
            
            if( mandatory ){
                if(  jcb.getText ().equals ( "" )){
                    showError  = true ;
                    jLabel3.setText ( errorValue );
                    jLabel3.setVisible ( true );
                }else{
                    showError  = false ;
                    jLabel3.setText ( "" );
                    jLabel3.setVisible ( false );
                }
            }
            
        }
    };

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
