/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trixware.erp.prodezydesktop.components;

/**
 *
 * @author Rajesh
 */
public class ProgressPanel extends javax.swing.JPanel {

    private String title, message ;
    
    /**
     * Creates new form ProgressPanel
     */
    public ProgressPanel () {
        initComponents ();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings( "unchecked" )
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setLayout(null);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        try{
            jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/trixware/erp/prodezydesktop/Utilities/assets/loading.gif")));
        }catch( NullPointerException e ){

        }
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        add(jLabel1);
        jLabel1.setBounds(10, 40, 85, 88);

        jLabel2.setFont(new java.awt.Font("Leelawadee UI", 0, 14)); // NOI18N
        add(jLabel2);
        jLabel2.setBounds(100, 20, 290, 30);

        jLabel3.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
        add(jLabel3);
        jLabel3.setBounds(100, 50, 290, 50);
    }// </editor-fold>//GEN-END:initComponents

    public String getTitle () {
        return title;
    }

    public void setTitle ( String title ) {
        jLabel2.setText( title );
        this.title = title;
    }

    public String getMessage () {
        
        return message;
    }

    public void setMessage ( String message ) {
        jLabel3.setText( message );
        this.message = message;
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
