/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trixware.erp.prodezydesktop.components;

import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author dell
 */
public class QualityPanel extends javax.swing.JPanel 
{
    int record_id1;

    public int getRecord_id1() 
    {
        return Integer.parseInt(record_id.getText());
    }

    public void setRecord_id1(int record_id1) 
    {
        this.record_id1 = record_id1;
        record_id.setText(""+record_id1);
    }
    int id;
    Float ull,lll;
    Float standard_mark;
    String param_name;
    ArrayList<String[]> uom=new ArrayList<>();

    public int getUom() 
    {
        return  Integer.parseInt(uom.get ( jComboBox1.getSelectedIndex () )[0]);
    }

    public void setUom(ArrayList<String[]> uom) 
    {
        this.uom = uom;
         for ( int i = 0 ; i < uom.size () ; i ++ ) 
        {
            jComboBox1.addItem ( uom.get ( i )[1]);
        }
        
    }

    public Float getStandard_mark() 
    {
        return Float.parseFloat(std_mark.getText());
    }

    public void setStandard_mark(Float standard_mark) 
    {
        this.standard_mark = standard_mark;
        std_mark.setText(""+standard_mark);
    }
    

    public String getParam_name() 
    {
        return jLabel1.getText();
                //param_name;
    }

    public void setParam_name(String param_name) 
    {
        this.param_name = param_name;
        jLabel1.setText(param_name);
    }

    public int getId() 
    {
        return Integer.parseInt(jLabel2.getText());
    }

    public void setId(int id) 
    {
        this.id = id;
        jLabel2.setText(id+"");
    }

    public Float getUll() 
    {
        return Float.parseFloat(Upper_limit.getText());
    }

    public void setUll(Float ull) 
    {
        this.ull = ull;
        Upper_limit.setText(""+ull);
    }

    public Float getLll() 
    {
        return  Float.parseFloat(Lower_limit.getText());
    }

    public void setLll(Float lll) 
    {
        this.lll = lll;
        Lower_limit.setText(""+lll);
    }

   
    /**
     * Creates new form RMQualityPanel
     */
    public QualityPanel() 
    {
        initComponents();
        jLabel2.setBounds(0, 0, 0, 0);
        jLabel2.setVisible(false);
        Lower_limit.addFocusListener ( f2 );  
        Upper_limit.addFocusListener(f2);
        std_mark.addFocusListener(f2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Lower_limit = new javax.swing.JTextField();
        Upper_limit = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        std_mark = new javax.swing.JTextField();
        record_id = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(300, 40));
        setLayout(null);
        add(jLabel1);
        jLabel1.setBounds(20, 10, 77, 30);

        Lower_limit.setPreferredSize(new java.awt.Dimension(30, 30));
        add(Lower_limit);
        Lower_limit.setBounds(210, 10, 30, 30);

        Upper_limit.setPreferredSize(new java.awt.Dimension(30, 30));
        Upper_limit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Upper_limitActionPerformed(evt);
            }
        });
        add(Upper_limit);
        Upper_limit.setBounds(250, 10, 30, 30);
        add(jLabel2);
        jLabel2.setBounds(269, 11, 0, 0);

        std_mark.setMinimumSize(new java.awt.Dimension(40, 30));
        std_mark.setPreferredSize(new java.awt.Dimension(30, 30));
        add(std_mark);
        std_mark.setBounds(110, 10, 30, 30);

        record_id.setText("jLabel3");
        record_id.setPreferredSize(new java.awt.Dimension(34, 0));
        add(record_id);
        record_id.setBounds(235, 11, 34, 0);

        add(jComboBox1);
        jComboBox1.setBounds(150, 10, 50, 20);
    }// </editor-fold>//GEN-END:initComponents

    private void Upper_limitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Upper_limitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Upper_limitActionPerformed

 FocusListener f2 = new FocusListener () 
    {
        @Override
        public void focusGained ( FocusEvent e ) {
//            throw new UnsupportedOperationException ( "Not supported yet." ); //To change body of generated methods, choose Tools | Templates.
            JTextField jcb = ( JTextField ) e.getSource ();    
            jcb.setText("");
        }

        @Override
        public void focusLost ( FocusEvent e ) {
        //    throw new UnsupportedOperationException ( "Not supported yet." ); //To Search Google or type URL
//change body of generated methods, choose Tools | Templates.
            JTextField jcb = ( JTextField ) e.getSource ();    
            String x = jcb.getText().trim ();
            
            if(x.equalsIgnoreCase ( ""))
            {
                x = "0";
            }
            
            try{    
                int num  = Integer.parseInt( String.valueOf( jcb.getText().toString() ) );
                    if( num<0  ){
                     jcb.setText(x);
                     
                    //evt.consume ();
                }
            }catch(NumberFormatException ex1){
                    jcb.setText(x);
//                    StaticValues.writer.writeExcel (MaintenanceTypePanel.class.getSimpleName () , MaintenanceTypePanel.class.getSimpleName () , ex1.getClass ().toString () , Thread.currentThread ().getStackTrace ()[ 1 ].getLineNumber () + "" , ex1.getMessage () , StaticValues.sdf2.format ( Calendar.getInstance ().getTime () ) );            
            }
        }
    };

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Lower_limit;
    private javax.swing.JTextField Upper_limit;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel record_id;
    private javax.swing.JTextField std_mark;
    // End of variables declaration//GEN-END:variables
}
