/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trixware.erp.prodezydesktop.components;

import java.awt.Dimension;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.util.ArrayList;
import javax.swing.BoxLayout;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JScrollPane;

/**
 *
 * @author Rajesh
 */
public class RadioForm extends javax.swing.JPanel {

    boolean mandatory = false; 
    boolean showError = false ;
    String labelValue, textValue, errorValue ;
    boolean selectedOrNot = false ;
    JScrollPane scroll;
    JPanel panel;
    JRadioButton jrb;
    
    /**
     * Creates new form TextInputForm
     */
    public RadioForm () {
        initComponents ();
        //jCheckBox1.addFocusListener ( valueListener );
        jLabel3.setVisible ( false );
    }

    public RadioForm (String labelVal,  boolean isMandatory, String errorString, boolean _selectedOrNot, String value) {
        initComponents ();
        mandatory = isMandatory ;
        jLabel2.setVisible ( mandatory );
        errorValue = errorString ;
        jLabel3.setToolTipText ( errorValue );
        jLabel1.setText( labelVal  ) ;
        jCheckBox1.addFocusListener ( valueListener );
        jLabel3.setVisible ( false );
        selectedOrNot = _selectedOrNot ;
        
        jCheckBox1.setSelected ( selectedOrNot );
        jCheckBox1.setActionCommand ( value);
    }
    
    public RadioForm (String labelVal,  boolean isMandatory, String errorString, ArrayList<String[]> cbListData) {
        initComponents ();
        mandatory = isMandatory ;
        jLabel2.setVisible ( mandatory );
        errorValue = errorString ;
        jLabel3.setToolTipText ( errorValue );
        jLabel1.setText( labelVal  ) ;
        jCheckBox1.addFocusListener ( valueListener );
        jLabel3.setVisible ( false );
        
        panel = new JPanel ();
        panel.setLayout ( new BoxLayout ( panel , BoxLayout.Y_AXIS ) );
        scroll = new JScrollPane ( panel ,
                JScrollPane.VERTICAL_SCROLLBAR_ALWAYS ,
                JScrollPane.HORIZONTAL_SCROLLBAR_NEVER );

        panel.setBounds (10, 17, 250, 93 );
        Dimension d = new Dimension (250, 30);
        
        for( int i=0; i<cbListData.size(); i++ ){
            jrb = new JRadioButton();
            jrb.setPreferredSize ( d );
        }
        
       
    }

    FocusListener valueListener = new FocusListener () {
        @Override
        public void focusGained ( FocusEvent e ) {
//            JTextField jcb = ( JTextField ) e.getSource ();
//            if( ! jcb.getText ().equals ( "")){
//                jcb.selectAll ();
//            }
//            showError  = false ;
//                    jLabel3.setText ("" );
//                    jLabel3.setVisible ( false );
        }

        @Override
        public void focusLost ( FocusEvent e ) {
//            JTextField jcb = ( JTextField ) e.getSource ();
//            if( mandatory ){
//                if(  jcb.getText ().equals ( "" )){
//                    showError  = true ;
//                    jLabel3.setText ( errorValue );
//                    jLabel3.setVisible ( true );
//                }else{
//                    showError  = false ;
//                    jLabel3.setText ( "" );
//                    jLabel3.setVisible ( false );
//                }
//            }
        }
    };
    
    public void setSelection( boolean State){
        jCheckBox1.setSelected ( State );
    }
    
    public boolean getSelection(){
        return jCheckBox1.isSelected () ;
    }
    
    public String getActionCommand(){
        return jCheckBox1.getActionCommand ().trim () ;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings( "unchecked" )
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(260, 64));
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
        jLabel1.setText("Label Name");
        add(jLabel1);
        jLabel1.setBounds(14, 0, 230, 16);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("*");
        add(jLabel2);
        jLabel2.setBounds(0, 0, 10, 19);

        jLabel3.setFont(new java.awt.Font("Leelawadee UI", 0, 10)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        add(jLabel3);
        jLabel3.setBounds(0, 50, 260, 15);

        jCheckBox1.setText("jCheckBox1");
        add(jCheckBox1);
        jCheckBox1.setBounds(10, 17, 250, 30);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
