/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trixware.erp.prodezydesktop.components;

import java.util.ArrayList;

/**
 *
 * @author Rajesh
 */
public class SpinnerForm extends javax.swing.JPanel {

    boolean mandatory = false; 
    boolean showError = false ;
    String labelValue, textValue, errorValue ;
    
    
    
    /**
     * Creates new form SpinnerForm
     */
    public SpinnerForm () {
        initComponents ();
         jLabel3.setVisible ( false );
    }
    
    public SpinnerForm( String labelVal,  boolean isMandatory, String errorString, ArrayList<String> data){
        initComponents ();
        mandatory = isMandatory ;
        jLabel2.setVisible ( mandatory );
        errorValue = errorString ;
        jLabel3.setToolTipText ( errorValue );
        jLabel1.setText( labelVal  ) ;
        jLabel3.setVisible ( false );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings( "unchecked" )
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("*");
        add(jLabel2);
        jLabel2.setBounds(0, 0, 10, 19);

        jLabel1.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
        jLabel1.setText("Label Name");
        add(jLabel1);
        jLabel1.setBounds(14, 0, 230, 16);

        jLabel3.setFont(new java.awt.Font("Leelawadee UI", 0, 10)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        add(jLabel3);
        jLabel3.setBounds(0, 50, 260, 15);

        jComboBox1.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(51, 51, 51));
        jComboBox1.setPreferredSize(new java.awt.Dimension(65, 30));
        add(jComboBox1);
        jComboBox1.setBounds(10, 16, 250, 32);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
