/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package components;

import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import javax.swing.JTextField;

/**
 *
 * @author Rajesh
 */
public class TextAreaInputForm extends javax.swing.JPanel {

    boolean mandatory = false; 
    boolean showError = false ;
    String labelValue, textValue, errorValue ;
    
    
    /**
     * Creates new form TextInputForm
     */
    public TextAreaInputForm () {
        initComponents ();
        jTextArea1.addFocusListener ( valueListener );
        jLabel3.setVisible ( false );
    }

    public TextAreaInputForm (String labelVal,  boolean isMandatory, String errorString) {
        initComponents ();
        mandatory = isMandatory ;
        jLabel2.setVisible ( mandatory );
        errorValue = errorString ;
        jLabel3.setToolTipText ( errorValue );
        jLabel1.setText( labelVal  ) ;
        jTextArea1.addFocusListener ( valueListener );
        jLabel3.setVisible ( false );
    }
    

    FocusListener valueListener = new FocusListener () {
        @Override
        public void focusGained ( FocusEvent e ) {
            JTextField jcb = ( JTextField ) e.getSource ();
            if( ! jcb.getText ().equals ( "")){
                jcb.selectAll ();
            }
            showError  = false ;
                    jLabel3.setText ("" );
                    jLabel3.setVisible ( false );
        }

        @Override
        public void focusLost ( FocusEvent e ) {
            JTextField jcb = ( JTextField ) e.getSource ();
            if( mandatory ){
                if(  jcb.getText ().equals ( "" )){
                    showError  = true ;
                    jLabel3.setText ( errorValue );
                    jLabel3.setVisible ( true );
                }else{
                    showError  = false ;
                    jLabel3.setText ( "" );
                    jLabel3.setVisible ( false );
                }
            }
        }
    };
    
    
    public String getText(){
        return jTextArea1.getText ().trim () ;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings( "unchecked" )
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(260, 128));
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
        jLabel1.setText("Label Name");
        add(jLabel1);
        jLabel1.setBounds(14, 0, 230, 16);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("*");
        add(jLabel2);
        jLabel2.setBounds(0, 0, 10, 19);

        jLabel3.setFont(new java.awt.Font("Leelawadee UI", 0, 10)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        add(jLabel3);
        jLabel3.setBounds(0, 113, 260, 15);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        add(jScrollPane1);
        jScrollPane1.setBounds(10, 17, 250, 93);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
