/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trixware.erp.prodezydesktop.components;

import trixware.erp.prodezydesktop.Model.TimeLossModel;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import javax.swing.JTextField;
import trixware.erp.prodezydesktop.Model.TimeLossModel;

/**
 *
 * @author Rajesh
 */
public class TimeLossDetailPanel extends javax.swing.JPanel {

    
    TimeLossModel t_l_Model ;
    
    int TRLid, minutes ;
    String reasonStr ;
    
    /**
     * Creates new form RMQtys
     */
    public TimeLossDetailPanel () {
        initComponents ();
        
        t_l_Model = new TimeLossModel();
   
        jTextField1.addKeyListener ( k );
        jTextField1.addFocusListener ( f2 );        
    }

    public int getTRLid () {
        return TRLid;
    }

    public void setTRLid ( int TRLid ) {
        this.TRLid = TRLid;
    }

    public int getMinutes () {
        return Integer.parseInt( jTextField1.getText () );
    }

    public void setMinutes ( int minutes ) {
        this.minutes = minutes;
        jTextField1.setText (minutes+"");
    }

    public String getReasonStr () {
        return reasonStr;
    }

    public void setReasonStr ( String reasonStr ) {
        this.reasonStr = reasonStr;
        jLabel2.setText(  reasonStr ) ;
    }
    
   
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings( "unchecked" )
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(255, 50));
        setLayout(null);

        jLabel1.setOpaque(true);
        add(jLabel1);
        jLabel1.setBounds(0, 0, 0, 0);
        add(jLabel2);
        jLabel2.setBounds(10, 5, 150, 30);

        jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField1FocusGained(evt);
            }
        });
        add(jTextField1);
        jTextField1.setBounds(160, 5, 50, 30);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1FocusGained

    KeyListener k = new KeyListener () {
        @Override
        public void keyTyped ( KeyEvent e ) {
           char enter = e.getKeyChar();
            if (!(Character.isDigit(enter))) {
                e.consume();
            }
        }

        @Override
        public void keyPressed ( KeyEvent e ) {
        }

        @Override
        public void keyReleased ( KeyEvent e ) {
        }
    };
    
    FocusListener f2 = new FocusListener () {
        @Override
        public void focusGained ( FocusEvent e ) {
//            throw new UnsupportedOperationException ( "Not supported yet." ); //To change body of generated methods, choose Tools | Templates.
            JTextField jcb = ( JTextField ) e.getSource ();    
            jcb.setText("");
        }

        @Override
        public void focusLost ( FocusEvent e ) {
        //    throw new UnsupportedOperationException ( "Not supported yet." ); //To Search Google or type URL
//change body of generated methods, choose Tools | Templates.
            JTextField jcb = ( JTextField ) e.getSource ();    
            String x = jcb.getText().trim ();
            
            if(x.equalsIgnoreCase ( "")){
                x = "0";
            }
            
            try{    
                int num  = Integer.parseInt( String.valueOf( jcb.getText().toString() ) );
                    if( num<0  ){
                     jcb.setText(x);
                     
                    //evt.consume ();
                }
            }catch(NumberFormatException ex1){
                    jcb.setText(x);
//                    StaticValues.writer.writeExcel (TimeLossDetailPanel.class.getSimpleName () , TimeLossDetailPanel.class.getSimpleName () , ex1.getClass ().toString () , Thread.currentThread ().getStackTrace ()[ 1 ].getLineNumber () + "" , ex1.getMessage () , StaticValues.sdf2.format ( Calendar.getInstance ().getTime () ) );            
            }
        }
    };

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel jLabel1;
    public static javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
