/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trixware.erp.prodezydesktop.examples.reports;

/**
 *
 * @author Rajesh
 */
public class PanelForDynamicGrpahs extends javax.swing.JPanel {

 

    public PanelForDynamicGrpahs ( String reportMasterType ) {
        initComponents ();
        
        Thread startDashboardMonitor = new Thread() {
        
            public void run(){
                    DynamicDashboard_One ddone = new DynamicDashboard_One( "Producton Quantity" ) ; 
                    ddone.setBounds(    0,260,430,300    ) ;
                    ddone.revalidate ();
                    ddone.repaint ();
                    add(    ddone ) ;

                    DynamicDashboard_Oee ddoee = new DynamicDashboard_Oee( "OEE" ) ; 
                    ddoee.setBounds(    0,10,250,250    ) ;
                    ddoee.revalidate ();
                    ddoee.repaint ();
                    add(    ddoee ) ;
                    
                    DynamicDashboard_Productivity ddprod = new DynamicDashboard_Productivity( "Productivity" ) ; 
                    ddprod.setBounds(   260,10,250,250    ) ;
                    ddprod.revalidate ();
                    ddprod.repaint ();
                    add(    ddprod ) ;
                    
                    DynamicDashboard_PMPH ddpmph = new DynamicDashboard_PMPH( "PMPH" ) ;
                    ddpmph.setBounds(   520,10,250,250    ) ;
                    ddpmph.revalidate ();
                    ddpmph.repaint ();
                    add(    ddpmph  ) ;
                    
                    DynamicDashboard_PPM ddppm = new DynamicDashboard_PPM( "PPM" ) ;
                    ddppm.setBounds(   780,10,250,300    ) ;
                    ddppm.revalidate ();
                    ddppm.repaint ();
                    add(    ddppm   ) ;
                    
            }
        } ;
        
        startDashboardMonitor.start() ;
    }

  
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings( "unchecked" )
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dateChooserDialog1 = new datechooser.beans.DateChooserDialog();

        setBackground(new java.awt.Color(255, 255, 255));
        setAutoscrolls(true);
        setMaximumSize(new java.awt.Dimension(1366, 760));
        setMinimumSize(new java.awt.Dimension(0, 0));
        setPreferredSize(new java.awt.Dimension(1282, 569));
        setLayout(null);
    }// </editor-fold>//GEN-END:initComponents

   
   
    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private datechooser.beans.DateChooserDialog dateChooserDialog1;
    // End of variables declaration//GEN-END:variables

    
     
}

